### ISSUE TITLE
Add Skew to mobile Futures Markets Stats

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#1006]
### Subject of the issue
The initial mobile design didn't include any Skew information (Open Interest Long and Short values and %). We want to add this to the Market Stats on mobile.

### Deliverables
- Remove ETH-PERP price from mobile Market Stats box, rename External Price to Live Price
- Move data around to match order as shown in mockup (see below) 
- Add Skew information to Market Stats on Mobile (see mockup)

### Rewards
40 SNX

**Comment by asherism** [comment]
<!-- Uploading "image.png"... —>

**Comment by asherism** [comment]
<img width="712" alt="image" src="https://user-images.githubusercontent.com/11524787/177832940-f70b9fe1-34ee-4da0-929a-92c7ac4db579.png">
