### ISSUE TITLE
Design synth redemption for v2

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#1021]
### Subject of the issue
From time to time, Synthetix deprecates assets, like has been the case recently with sDEFI. Users can redeem any leftover deprecated synths. V1 had this baked into the UI, however for V2 we do not have this function yet.

As a temporary solution, a simple "Redeem deprecated synths" button is added to the Synth Exchange, see ticket #1016 

### Screenshot of how it looked in v1
![deprec](https://user-images.githubusercontent.com/548702/174092386-0c5b3683-68e3-46fe-8472-a237ec6e672b.png)

### Deliverables
- Evaluate where a simplified synth redemption fits into the v2 design
- Create a design for synth redemption

**Comment by asherism** [comment]
No longer necessary. Archiving.
