### ISSUE TITLE
Improve MarketDetails for smaller screens

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#1024]
### Subject of the issue
a) On smaller/tablet size screens, the `MarketDetails` container metrics wrap out of their container. This should be avoided by improving the layout of the container. See comments below in this ticket.

![Image](https://user-images.githubusercontent.com/548702/180887154-6fa7c3a5-bd64-4eca-a82d-dabac8265bb4.png)

b) The padding of the tooltip for the Oracle price ("Last Update: nn:nn") is off compared to all other default tooltips. This should be fixed. See screenshots below:

Current padding of tooltip:
<img width="591" alt="Screen Shot 2022-07-29 at 11 20 53" src="https://user-images.githubusercontent.com/548702/181780649-844d1e3e-915c-4303-b4c8-a27a0ebed323.png">

Padding should be the same as other tooltips, e.g.:
<img width="591" alt="Screen Shot 2022-07-29 at 11 20 57" src="https://user-images.githubusercontent.com/548702/181780728-276f21f2-21ff-4983-9d32-dc159ed486fe.png">

### Deliverables
- Fix the "Last update" oracle price tooltip padding
- Add a nowrap white-space property to all metrics
- Make sure container scrolls horizontally when space is scarce
- Make sure tooltips are not clipped by horizontal scrolling and show correctly (see comment below)

### Reward
40 SNX

**Comment by platschi** [comment]
This should be avoided:

![Image](https://user-images.githubusercontent.com/548702/180887154-6fa7c3a5-bd64-4eca-a82d-dabac8265bb4.png)

**Comment by asherism** [comment]
All metrics should have a nowrap white-space property and the container should simply scroll horizontally when space is scarce. Note: scrolling the container contents will clip the tooltips- final fix should account for this.
