### ISSUE TITLE
Fix price feed for atomic exchange

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#1051]
### Subject of the issue
Atomic Swaps on Kwenta Exchange use the chainlink price. We should use the `value` number instead.

> that `value` number is the price user will be getting when exchange atomically, `systemValue` is the chainlink price `systemSourceRate` is chainlink price of source and `systemDestinateRate` is the chainlink price of destination
> `ExchangeRatesWithDexPricing`

### Deliverables
- Make sure atomic exchange price feed uses `value`

**Comment by platschi** [comment]
Note: The current implementation of `useExchange.ts` needs to be cleaned up first before adding the Atomic Price Feed. Ticket has been paused until then.

**Comment by LeifuChen** [comment]
> Note: The current implementation of `useExchange.ts` needs to be cleaned up first before adding the Atomic Price Feed. Ticket has been paused until then.
> 
> / Edit: Refactor done, re-evaluate this PR

I will create a new PR to add this feature.
