### ISSUE TITLE
Exchange on Mobile (Phase #4)

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#1062]
Implement a mobile friendly version of the Swap UI (`/exchange/`)

### Deliverables
- Needs design from Yashar to begin with
- Make sure synth selection modal is mobile friendly
- More tbd

**Comment by asherism** [comment]
https://www.figma.com/file/YWU3PMsnqZaqr1gABgAFJK/UI-Refresh?node-id=4195%3A25327
