### ISSUE TITLE
Improve loading state

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#1174]
### Subject of the issue
This is a follow up on #1162. We should fix the "loading" state so we don't see the empty states before a wallet is fully connected. For example, if you're connected and refresh the homepage you'll see the "empty" state and it will fill with data when the query returns.

We already have a loading element that can display, but we don't pass "Loading..." to the component correctly. If we have the states handled, we can pass any kind of loading element (like a shimmer).

### Deliverables

- [ ] add an isLoading state to all tables that fetch data
- [ ] add some conditions to the "no results" message to avoid showing something in states before fully loaded (network is detected, account is connected)

**Comment by Tburm** [comment]
Key updates are:
* Add an `isLoading` state to all tables that fetch data
* Add some conditions to the "no results" message to avoid showing something in states before fully loaded (network is detected, account is connected)
