### ISSUE TITLE
Remove arrow indicator for funding

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#1223]
### Subject of the issue
Remove the arrow indicator in the FuturesMarketTable, as it it confusing traders:

> Anyone else feel like when they see up or down arrow next to a number you expect it to be a "change", but the funding rate shown is not change, but absolute

### Design
Example how it should be (ex. ETH-PERP):

![Image](https://user-images.githubusercontent.com/548702/182870405-d2175d0b-5304-4cc0-9def-c6863b92042c.png)

### Deliverables
- Remove up/down arrow svg for 1H Funding Rate on Futures Markets

### Bounty
25 SNX

**Comment by snehashish-ghosh98** [comment]
Hello. I would like to work on this issue. I went through the website and tried to inspect and remove the arrow. I am attaching the screenshot. 
P.S.  I am a complete beginner in the GitHub space so it would be really nice if you could guide me in case of any error.
![image](https://user-images.githubusercontent.com/106345869/182947711-281c6e28-ac40-4e5d-bc8a-3e42f8a9599f.png)

**Comment by platschi** [comment]
> Hello. I would like to work on this issue. I went through the website and tried to inspect and remove the arrow. I am attaching the screenshot. P.S. I am a complete beginner in the GitHub space so it would be really nice if you could guide me in case of any error.

Hi @snehashish-ghosh98! Thanks for your interest to work on issues! In order to grab available tickest, please join our discord `#devdao-chat` channel, where devDAO members can claim available tickets to work on.

You can all information in our contribution guideline here in our docs: https://docs.kwenta.io/dao/contribute/devdao-contribute
