### ISSUE TITLE
Improve overall app error handling and display

### ISSUE THREAD

**Issue by avclarke** [Kwenta/kwenta#1298]
### Feature Proposal
Improved error feedback 

### Rationale
Error displays are currently inconsistent, can contain long unfriendly error messages and not efficient to implement.

### Implementation
Implement an error notification component, which would overlay the whole app (similar to the tx notifier) and receive notification events from any component. Could be good to use React portals for this.

The error notifier would also handle parsing messages from smart contract failures and will take a more generic fallback message in the case it receives an error it cannot parse. Example function signature on the error handler:

```
notifyError(error: Error, fallback: string)
```

### Error message mapping

There are a number of errors that can be returned during transactions that are currently just shown to the users as generic failed, leaving them unaware of what actually went wrong and difficult for us to debug. To improve the feedback we should identify specific errors we are aware of and feedback more helpful and user friendly messaging. 

**Generic erros**
```INSUFFICIENT_FINDS ``` - Not enough ETH to cover gas for the tx

**Exchange**
```Surpassed volume limit``` - User cannot exchange more than 100k sUSD when doing atomic swaps

**Futures**
```Max market size exceeded``` - OI cap reached

**Comment by platschi** [comment]
Related and includes a list of common errors: #491

**Comment by platschi** [comment]
Design ready in #1453
