### ISSUE TITLE
Display limit and stop orders on trading view chart

### ISSUE THREAD

**Issue by avclarke** [Kwenta/kwenta#1386]
Design requirements:

- Display of the different order types in the trading view chart.
- Option to show and hide different types.

**Comment by asherism** [comment]
https://www.figma.com/file/YWU3PMsnqZaqr1gABgAFJK/UI-Refresh?node-id=6169%3A30919

**Comment by asherism** [comment]
<img width="859" alt="image" src="https://user-images.githubusercontent.com/11524787/197033860-92cd0616-0f62-42bc-a0b3-e6e97ad39978.png">
