### ISSUE TITLE
Leaderboard search box doesn't find accounts starting with 0xf

### ISSUE THREAD

**Issue by amphoria** [Kwenta/kwenta#1398]
### Subject of the issue
Typing 0xf into the Leaderboard search box doesn't return any results even though 0xf59B2359a33D9777f381d5044DAF47F3e309f018 is a valid account which should appear

### Your environment
* L2
* Chrome 105.0.5195.102

### Expected behaviour
A list of accounts starting 0xf should appear

### Actual behaviour
The list is empty, but at least one account should appear. The account can be accessed from the url https://kwenta.io/leaderboard/?trader=0xf59B2359a33D9777f381d5044DAF47F3e309f018

### Steps to reproduce
Go to Leaderboard page and enter 0xf into the search box

**Comment by platschi** [comment]
Issue seems to be resolved. closing ticket.

![Screenshot 2022-10-31 at 10 14 05](https://user-images.githubusercontent.com/548702/199016227-e16e3957-2a96-44b7-969a-3bcba0b9494d.png)
