### ISSUE TITLE
UX: Market Details Card Contract address broken on L2

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#14]
- **Issue**: On L2 Optimism Mainnet, the token contract link is broken, it generates an <code>https://unknown.etherscan.io/token/0x...</code> url.

https://github.com/Kwenta/kwenta/blob/963eb7e44903b631fa748ecd5379353adf376c08/sections/exchange/TradeCard/Cards/MarketDetailsCard.tsx#L131

- **Expected behavior:** Correct link should be <code>https://optimistic.etherscan.io/token/0x...</code>

**Steps to reproduce:**

1. On Kwenta.io L2 (Optimism Mainnet), go to Exchange
2. On Exchange, select any two pairs & show the "Double" Charts
3. Below the chart in the "Market Details" card, click the (broken) Contract link.
4. Edit: Same with Price Feed URL.

**Comment by JChiaramonte7** [comment]
Thanks @platschi !

@kmeraz We need to change any remaning `etherscanInstance` to `blockexplorerInstance` and remove the etherscan provider from our dapp.

**Comment by kmeraz** [comment]
Thanks @platschi !

This issue will be addressed by this PR: https://github.com/Kwenta/kwenta/pull/17

**Comment by platschi** [comment]
Commit https://github.com/Kwenta/kwenta/commit/905a3eb8806defb1d63d7f111498a8e981a515f0  fixed the domain in the link, but there's still two issues:

- [ ] Contract URL includes a double slash `//`, no idea if that's intentional but at least it works. E.g. for sUSD.: ``https://explorer.optimism.io//token/0x8c6f28f2F1A3C87F0f938b96d27520d9751ec8d9``

- [ ] Price Feed URLs link to an 404 error page

(Tested on kwenta.io L2)

**Comment by JChiaramonte7** [comment]
>  Contract URL includes a double slash //, no idea if that's intentional but at least it works. E.g. for sUSD.: https://explorer.optimism.io//token/0x8c6f28f2F1A3C87F0f938b96d27520d9751ec8d9

>  Price Feed URLs link to an 404 error page

`Thanks @platschi. Going to add a "Help Wanted" label to this one since it isn't fully resolved yet.

**Comment by platschi** [comment]
> Contract URL includes a double slash `//`, no idea if that's intentional but at least it works. E.g. for sUSD.: `https://explorer.optimism.io//token/0x8c6f28f2F1A3C87F0f938b96d27520d9751ec8d9`

Looks like the code fetches the Optimism Explorer URL from below package, which lists the Optimism Explorer URL with a trailing slash. Removing it in within the package might break links elsewhere, though.

https://github.com/Synthetixio/js-monorepo/blob/0a08c55610060e3cee7acf95e1cfc429a956354d/packages/optimism-networks/src/constants.ts#L18
