### ISSUE TITLE
Rainbowkit: Add injected wallet connector & set default provider through wallet

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#1467]
1) Brave Browser does not show up nor works anymore correctly with Kwenta.
2) We should try to push the provider back on the wallet if possible.

## Deliverables
- Add injected wallet connector to support different injected wallets.
- Bump rainbowkit, wagmi and dependencies to latest versions*
- Make sure Brave Browser support is working
- Investigate options and try to use wallet provider as default instead of Kwenta BlastAPI (BYOP better for decentralization)

e.g. rainbowkit 0.7.0 introduced tree shaking of individual wallets, see [rainbowkit/releases](https://github.com/rainbow-me/rainbowkit/releases)

**Comment by LeifuChen** [comment]
@platschi shall we close this ticket?
