### ISSUE TITLE
GnosisSafe wallet auto connect broken

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#1545]
### Subject of the issue
From dHedge:
> GnosisSafe wallet auto connect connects to MetaMask instead of Gnosis Safe when opening Kwenta not on the main page, but on e.g. https://kwenta.io/market/?accountType=isolated_margin&asset=sETH

### Deliverables
- Make sure GnosisSafe wallet auto connect also works when visiting other pages than the main page

**Comment by LeifuChen** [comment]
@platschi we can close this ticket.
