### ISSUE TITLE
Improve app operational status feedback

### ISSUE THREAD

**Issue by avclarke** [Kwenta/kwenta#1599]
### Feature Proposal
We should better indicate to users what state the app is in and limit functionality when the app is not useable due to incomplete data from failed queries or issues with 3rd party services etc.

### Rationale
Currently queries can fail leaving the app in a state of incomplete data but leaving the user completely unaware, causing them think the app is fully functional when it's not. 

### Implementation
- Show an indicator when components are fetching data required to populate and become operational
- Show a failed status when essential queries fail and data is missing
- Disable certain functionality when the required data is unavailable
- Add a retry button to allow the user to attempt to retry fetching the data
- Add a system status indicator so we can let users knows when some infrastructure is down or limited

**Comment by platschi** [comment]
Example from Kraken:

<img width="1794" alt="Screenshot 2023-01-09 at 12 13 04" src="https://user-images.githubusercontent.com/548702/211341302-cfba58c9-ecd8-43f5-a721-7ff10cabb791.png">

**Comment by asherism** [comment]
archiving ticket as this functionality will be part of the upcoming redesign
