### ISSUE TITLE
Add in app gas estimations for some transactions

### ISSUE THREAD

**Issue by avclarke** [Kwenta/kwenta#1606]
Some transactions have been experiencing out of gas errors, mostly `distributeMargin` in cross margin futures and `swapSynthSwap` and `swapOneInch` in exchange. It's not clear why Metamask sometimes under estimates the gas usage and what dynamic part of the contract call causes the amount to change.

To reduce the failures we should start estimating the gas limit ourselves for these transactions and add a bigger buffer.

**Comment by platschi** [comment]
Experiencing the same with Stake Escrow, for example

**Comment by platschi** [comment]
- Insure all right txs are pushed through tx service to estimate correct gas
