### ISSUE TITLE
Landing page: Fix typo

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#1633]
### Subject of the issue
On the landing page, it states *Gain exposure to a variety of asset*.   This should be *assets* (plural).

<img width="1177" alt="Screenshot 2022-11-18 at 14 09 35" src="https://user-images.githubusercontent.com/548702/202762072-aa55147b-86c7-401d-b514-7ab7aaef2187.png">

### Deliverables
- Fix the typo on the landing page

### Bounty
60 $OP

**Comment by rootz491** [comment]
can i work on this one?
