### ISSUE TITLE
Staking UI: Trading Rewards Button

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#1643]
### Subject of the issue
The Trading Rewards "Claim" button currently is labelled as "Claim All". We should streamline the design with the Staking tab, where the Claim button states "Claim" to have an coherent design.

<img width="528" alt="Screenshot 2022-11-19 at 09 49 20" src="https://user-images.githubusercontent.com/548702/202851672-18c2b84c-2800-4461-8682-d601b408763a.png">

### Deliverables
- Rename _Claim All_ button label to _Claim_ for Trading Rewards tab on the Staking page

### Bounty
60 $OP

**Comment by MukulKolpe** [comment]
Hey @platschi, can I work on this issue?

**Comment by platschi** [comment]
@MukulKolpe @biendeveloper much appreciated but we distribute tickets for the devDAO on our Discord, see also https://docs.kwenta.io/developers/devdao-contribute
