### ISSUE TITLE
Staking UI Polish

### ISSUE THREAD

**Issue by avclarke** [Kwenta/kwenta#1658]
There's been some feedback that there is room for improvement in the staking UI / UX, let's review the designs and frontend, check they are in sync and frontend implemented fully and then see if there some areas for improvement.

**Comment by platschi** [comment]
### Deliverables

In general, follow the Figma design as close as possible. For design considerations/examples, discuss with @asherism.

- [ ] Staking modal: Balance values should be a visible, clickable link (different shade for links, underscore), visible element when hovering over balance(?)
- [ ] Sort tabs by usage:  Staking, Escrow, Trading Rewards, Redemption
- [ ] Make top boxes clickable to bring you to the respective tab. So if you click "Escrow", "Staked Escrow" or "Vestable", it should switch to Staking UI "Escrow" tab, "Claimable" to the "Staking tab", and so on.
- [ ] Question: Why vesting table layout different from other table designs on the website? Streamline table design with other tables (e.g. see leaderboard as reference). Discuss with Yashar if necessary
- [ ] Fix background of Kwenta dApp dark theme to Figma design
- [ ] Bump contrast on text on dark theme (see Figma how it should be, partly solved with fixing background)

On Dashboard (left navigation):

- [ ] Remove gradient style
- [ ] Update button styles to latest design specifications
- [ ] Remove Governance from the list
- [ ] Update header colors etc. to current design
