### ISSUE TITLE
Make trading rewards more prominent and show how they offsets fees

### ISSUE THREAD

**Issue by avclarke** [Kwenta/kwenta#1675]
**Highlight trading rewards in cross margin to counter fees**

_Andrew requested rewards should be extra prominent and potentially a consistent UI component used throughout the app to promote / track how many rewards you are on. It can also have it's own sub brand / color so it can be instantly identified as rewards_

Now there are trading rewards to offset fees we need to promote this in the cross margin UI. This should be included next to the fees in both the trade panel and confirmation panel.

- [x] It should also be made clear that in order to earn from fees you need to have Kwenta staked.

- [ ] Would also be good to think about where else to indicate that cross margin includes trading rewards, potentially in the navigation and dashboard.

- [ ] #1846

Showing trading rewards on the dashboard trading page would help to increase visibility and awareness of rewards and how it offsets fees.

- [ ] **Display trading rewards on the staking dashboard**

Currently the trading rewards are hidden behind the tab, it would be nice for them to be visible as one of the overview values on the staking page landing.

- [x] **Stake to earn trading rewards explainer**

Under the trading rewards tab on the dashboard it's not clear that you need to be staking in order to accrue fees. We should add some clear indicator here that staking is required and how the rewards are calculated based on staked amount.

**Comment by platschi** [comment]
Relevant PR #1751
