### ISSUE TITLE
Futures: Improve visibility of Deposit/Withdraw option on UI

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#1686]
### Subject of the issue
In the past weeks, we received frequent questions from users not able to find the option to deposit or withdraw sUSD to their isolated resp. cross margin account in order to trade on Kwenta. The two arrows seem not intuitive enough for users to connect with deposit/withdraw.

<img width="930" alt="with" src="https://user-images.githubusercontent.com/548702/204295518-42800088-dca7-4cb7-a9be-8d1a04abc894.png">

### Deliverables
- Evaluate current deposit/withdraw design and research improved ways to show this option on UI
- Create new design
- Implement new design

**Comment by avclarke** [comment]
As the conversation continued the user mentioned they were trying to withdraw from the dashboard, so I think it was more an issue of accessibility in other places rather than visibility in the market page. Personally I'd be happy to keep this as is for now. @platschi @asherism
