### ISSUE TITLE
duplicate markets on testnet (both on L1 and L2)

### ISSUE THREAD

**Issue by zhyd1997** [Kwenta/kwenta#1715]
### Subject of the issue
`ETH-PERP` and `BTC-PERP` are duplicated.

### Your environment
* Network used (Mainnet? L2?)
* Which browser and its version

### Expected behaviour
Only show `ETH-PERP` and `BTC-PERP` once.

### Actual behaviour
But it shows twice:

<img width="1055" alt="Screen Shot 2022-12-04 at 08 59 16" src="https://user-images.githubusercontent.com/31362988/205468688-af23038a-abed-4cc9-b8d9-5c97c365f624.png">

**and** the `isolated margin` also is doubled, eg, I have only `$50` but it shows `$100`.

### Steps to reproduce
Go to `dashboard` page: https://kwenta.eth.limo/dashboard or https://dev.kwenta.io/dashboard/.

**Comment by LeifuChen** [comment]
Thanks for the report. This is because of perp v2 migration. 
Here is the fix: https://github.com/Kwenta/kwenta/pull/1712
