### ISSUE TITLE
Rest API Endpoint for Kwenta token stats

### ISSUE THREAD

**Issue by Marko-roy** [Kwenta/kwenta#1746]
### Subject of the issue
Create a generic rest API that keeps track of the $KWENTA tokens total circulating supply,

### Rationale
Coingecko along with most token tracker sites require an API endpoint to keep track of tokens stats such as circulating supply and total supply. 

### Implementation
Create the API and work with core contributors to deploy & host.

Reference example: [http://api.mainnet-beta.solana.com/v0/circulating-supply](url)

### Bounty
200 $OP

**Comment by ef3n9r98** [comment]
Hi @Marko-ro, it's great to see that you're attaching a bounty to issues!  I know some devs who'd be interested in working on this - just to be sure, is $OP $Optimism? Thus making the bounty would be roughly $170 USD? 

I'll put this issue up on [OpenQ](http://www.openq.dev).

Thanks!

**Comment by kethcode** [comment]
> Hi @Marko-ro, it's great to see that you're attaching a bounty to issues! I know some devs who'd be interested in working on this - just to be sure, is $OP $Optimism? Thus making the bounty would be roughly $170 USD?
> 
> I'll put this issue up on [OpenQ](http://www.openq.dev).
> 
> Thanks!

Kwenta already has a ticket and bounty system in place.  You may consider joining the discord and checking out the devdao section.

**Comment by kethcode** [comment]
totalSupply did not take long.  Still working out an appropriate caching frequency based on update rate.

circulatingSupply is still in progress; would like more clarity on what we want this to cover.

finishing up clustering comm for scaling.

anything else we want in v0?  this is a little thin for an API.

**Comment by kethcode** [comment]
i have these 3 endpoints workng right now.  just working on scaling and caching now

![image](https://user-images.githubusercontent.com/94415863/209508341-21c39bb0-abf5-4bf6-8111-fff5174efa82.png)

**Comment by kethcode** [comment]
https://github.com/kethcode/kapi for code.  will continue my commits there until we decide a location.

**Comment by kethcode** [comment]
deployed to heroku

https://kwenta-api.herokuapp.com/v0/totalSupply
https://kwenta-api.herokuapp.com/v0/circulatingSupply
https://kwenta-api.herokuapp.com/v0/stakedSupply

**Comment by kethcode** [comment]
Ive changed my mind on some of the naming of the endpoints while I was adding a couple more, so dont use these for anything permanent yet.

**Comment by kethcode** [comment]
ok, this is better.  

API Table of Contents
https://kwenta-api.herokuapp.com/

Kwenta API v0:
https://kwenta-api.herokuapp.com/v0/supply-total
https://kwenta-api.herokuapp.com/v0/supply-circulating
https://kwenta-api.herokuapp.com/v0/supply-locked
https://kwenta-api.herokuapp.com/v0/supply-staked
https://kwenta-api.herokuapp.com/v0/supply-staked-circulating
https://kwenta-api.herokuapp.com/v0/supply-staked-locked

**Comment by kethcode** [comment]
ok, caching is done now too.  ticket complete

**Comment by kethcode** [comment]
added:

Dev Only (RPC Expensive, Only Use As Needed):
https://kwenta-api.herokuapp.com/v0/supply-refresh-cache

**Comment by 0xwalde** [comment]
@kethcode just wondering, is there any reason this should be a standalone API deployment instead of part of the existing Next.js app? It looks like we already have a couple of API Routes in there (although they're not exposed via IPFS):

`/api/commodityPrice`
`/api/forexPrice`

Not saying we have to do that, but you could probably reuse more of the contract info and utilities already built into the main Kwenta repo if it was an API route. Plus not having to manage separate deployments would be nice.

**Comment by kethcode** [comment]
Had not considered that, and did not k ow we had api endpoints already. I'll look into redoing it all over there.

**Comment by kethcode** [comment]
was just solving the problem as described.  the api endpoints you reference don't even work anymore, as I understand it, but i'll admit I didn't look into integrating with the existing codebase for such a simple task.

we'll see what the cc's say.  I can migrate the endpoints at a future time, and use the ones i've already deployed and hosted to solve the immediate coingecko issue.  i'm already managing 2 other heroku deployments for kwenta, so this just goes on the list.

**Comment by 0xwalde** [comment]
Cool, no worries-- just a suggestion! The `forexPrice` one does at least work locally, but it's not linked up in IPFS so I'm assuming neither endpoint is actually used by the app anymore. In any case though I think it would be as easy as adding a new IPFS link for the `/api` route to make such endpoints actually callable.

Totally makes sense to do this in phases, and I didn't realize we already ancillary deployments running to support the app already which makes it less of an issues to add another one 🙂

**Comment by kethcode** [comment]
there are certainly better ways to do it.  static routes in a single file is pretty bleh, and js instead of ts is <.<, and express instead of fastly, and and and.  I'll gladly iterate on this as another ticket, or work on migrating it later.
