### ISSUE TITLE
Staking UI: Add commit hash

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#1766]
### Subject of the issue
On most pages on Kwenta, we show a commit hash at the bottom to make troubleshooting easier. The Staking UI page currently does not show this commit.

### Expected behaviour
![Screenshot 2022-12-16 at 10 28 48](https://user-images.githubusercontent.com/548702/208108798-a66db9e7-0d76-46ea-bd54-5b7a7f11ea01.png)

### Actual behaviour
![Screenshot 2022-12-16 at 10 29 04](https://user-images.githubusercontent.com/548702/208108830-6f0e2a2e-fad4-4022-90a8-0d3444fb5d3d.png)

### Steps to reproduce

- [ ] Make sure the commit hash is shown on the Staking UI below the modals of each tab.
- [ ] Make sure the commit hash is visible on both desktop and mobile

### Bounty
100 $OP

**Comment by metadiver** [comment]
hi @platschi, I'm a new contributor, can I work on this issue?

**Comment by platschi** [comment]
> hi @platschi, I'm a new contributor, can I work on this issue?

You can claim new tickets for the devDAO on our Discord. Please see for all information on how to participate our docs at https://docs.kwenta.io/developers/devdao-contribute
