### ISSUE TITLE
Make deposit button more obvious when user has no sUSD in market or cm account

### ISSUE THREAD

**Issue by avclarke** [Kwenta/kwenta#1794]
It should be a much stronger CTA in the trade panel to deposit when the user has no funds as new users often struggle to recognise the small transfer button next to the balance.

**Comment by asherism** [comment]
i'm thinking something like:
<img width="418" alt="image" src="https://user-images.githubusercontent.com/11524787/209049230-ed3b6deb-9674-46f2-97d3-671596f46c31.png">


or just replace it completely:
<img width="436" alt="image" src="https://user-images.githubusercontent.com/11524787/209049144-8f84bad4-517f-4f2f-afa3-d555108793d0.png">

**Comment by avclarke** [comment]
Looks good Yashar, I went with the version that takes up the whole width and replaces the header. Just need the light mode version. https://github.com/Kwenta/kwenta/pull/1802

**Comment by asherism** [comment]
<img width="490" alt="image" src="https://user-images.githubusercontent.com/11524787/209191788-9a1d1d3e-62c2-43d6-93f2-1fdbf74168c0.png">
same colour on light mode but what you've currently implemented totally works as  well
