### ISSUE TITLE
Trade confirmation modal opens with zero values

### ISSUE THREAD

**Issue by avclarke** [Kwenta/kwenta#1845]
### Subject of the issue
Users are able to select "open position" and open the confirmation modal when they have no size set. 

![2023-01-07_131229](https://user-images.githubusercontent.com/3802342/211148988-32b81d1a-7d74-4a80-bc08-386b8a83239b.jpeg)

### Expected behaviour
Confirm modal shouldn't open with zero values and "open position" or "modify" buttons should be disabled when no size set.

### Steps to reproduce
Click "open position" without setting a size value.

**Comment by electricbabe** [comment]
I believe this one was fixed already. I was not able to reproduce it.
