### ISSUE TITLE
Perps v2: Hookup Pyth historical price data for trading view

### ISSUE THREAD

**Issue by avclarke** [Kwenta/kwenta#1867]
### Feature Proposal
Pyth offer an api to fetch OHLC data for populating candlestick charts, we should hook this up to our own chart instead of displaying on chain prices from the subgraph. 

### Rationale
Current chart data is not inline with the offchain prices used in v2 and subgraph can be unreliable in syncing.

### Implementation
Endpoint provided by Pyth:  https://pyth-api.vintage-orange-muffin.com/tradingview/history?from=1671494400&resolution=1&symbol=GALA%2FUSD&to=1671495540

No documentation was provided so may need to reach out to them if more info needed but it follows the trading view spec here: https://www.tradingview.com/rest-api-spec/

**Comment by Tburm** [comment]
This work has been completed, however on hooking it up the API returns data slowly compared to our current implementation. For large timeframes, the API is not usable. We reached out to Pyth to continue improving this endpoint for our use case.

**Comment by Tburm** [comment]
See branch on this closed PR for more details: #2083

**Comment by Tburm** [comment]
@platschi I can take a look this week. The branch is still there, but it's currently hooked up to _only_ the pyth price. The last discussion we had was to hook up low timeframes to pyth and higher timeframes to the subgraph.

I'll look into how feasible it is to finish this week, I think it is just adding back some of the subgraph query logic and updating the existing branch.
