### ISSUE TITLE
Exchange: Can enter non number characters in number input

### ISSUE THREAD

**Issue by avclarke** [Kwenta/kwenta#1943]
### Subject of the issue
Since changing the number input type to "text" to deal with localisation issues there is now an issue where users can type any character and cause an error in trying to convert invalid value to Wei.

https://kwenta.sentry.io/issues/3897297109/?project=4504363261362177&query=is%3Aunresolved&referrer=issue-stream

### Expected behaviour
Non number characters should be prevented from typing in the number input

### Actual behaviour
Any characters can be typed

### Steps to reproduce
When in local dev mode type any character in the input and you'll get an error pop up. (This error is silent in prod)

**Comment by platschi** [comment]
#1944 might be related to this
