### ISSUE TITLE
Exchange: Quote not calculated on first attempt

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#1944]
### Subject of the issue
When visiting the Exchange and selecting a base and quote token, and then clicking "Max" for the base token, the values for the quote do not calculate.

This only works if the user deletes the base values and enters a value manually.

### Your environment
* OP Mainnet
* Chrome, latest

### Expected behaviour
On click of "Max", both base and quote should be calculated immediately.

### Actual behaviour

https://user-images.githubusercontent.com/548702/216041346-a692df20-840c-44e7-9686-815948b2e19f.mov

### Steps to reproduce
1. Visit Kwenta
2. Connect wallet with some token holdings
3. Visit Exchange, select base token (of which wallet holds tokens) and quote token
4. Click MAX

**Comment by LeifuChen** [comment]
This is more like an RPC issue, but returning a more helpful message to the user would be better.
