### ISSUE TITLE
Add IPFS Pin to Crust Network

### ISSUE THREAD

**Issue by newnewnewsms** [Kwenta/kwenta#203]
### Feature Proposal

Since Kwenta has already deployed the frontend to IPFS, I propose to **pin the CID to Crust Network** which helps to **increase the number of replicas for the frontend files on IPFS** in a decentralized way.

Crust is a decentralized storage network based on IPFS with 7000+ IPFS nodes and over 2000+ PB IPFS storage volumes. The motivation of this proposal is to **ensure high availability and decentralization of Kwenta frontend** on IPFS since files will be distributed to 30+ IPFS nodes in Crust Network and all the nodes in Crust Network are distributed and decentralized.

### Rationale

1. High Availability: frontend files will be distributed to 30+ IPFS nodes in Crust Network;
2. Decentralization: all the nodes in Crust Network are distributed and decentralized;

### Implementation

Add Crust IPFS Pinning action to Kwenta frontend's Github workflows.

Examples:

1. Uniswap is using the Github Action -- ipfs-crust-action to Pin the Dapp to IPFS in Github Action way. Here is the code ref(https://github.com/Uniswap/interface/blob/main/.github/workflows/release.yaml#L58-L64), and here is the issue introduced why Uniswap uses Crust([CI] Uniswap Interface decentralized IPFS pin [CI] Uniswap Interface decentralized IPFS pin [CI] Uniswap Interface decentralized IPFS pin Uniswap/interface#1339)
2. AAVE is using the Github Action -- ipfs-crust-action to Pin the Dapp to IPFS in Github Action way. Here is the code ref(https://github.com/aave/aave-ui/blob/d50d331c9ddbfaa6bb35e091083712b17e266496/.github/workflows/deploy.yml#L40)

I can work on that and start a PR and make sure there will be no conflict with the current branch. For storage fees, I received financial support from Crust's on-chain treasury. Hope to hear the admins' thoughts.

**Comment by platschi** [comment]
To consider for #879
