### ISSUE TITLE
CM v2: Update the subgraph to index cross margin v2 events

### ISSUE THREAD

**Issue by avclarke** [Kwenta/kwenta#2035]
Update the subgraph to support cross margin v2:

- [x] Account creation
- [x] Trade history
- [x] Regular orders
- [x] Conditional orders
- [x] Transfer history
- [x] Order Types

**Comment by Tburm** [comment]
@avclarke The hosted service subgraphs have been updated with some of this info:
* https://thegraph.com/hosted-service/subgraph/kwenta/optimism-perps
* https://thegraph.com/hosted-service/subgraph/kwenta/optimism-goerli-perps

Currently they include accounts with a new `SmartMarginAccount` entity, and all other entities have had the `account`, `abstractAccount`, and `accountType` fields updated to reflect this.

I'll continue working on the other events (margin transfers, advanced orders)

**Comment by Tburm** [comment]
Transfer events added in [this PR](https://github.com/Kwenta/kwenta-subgraph/pull/134)
