### ISSUE TITLE
UX Bug: Make it more obvious when an order is pending

### ISSUE THREAD

**Issue by avclarke** [Kwenta/kwenta#2067]
### Subject of the issue
Users are reporting submitting multiple orders because it is not clear they need to wait for their order to execute at the delayed time.

### Proposed solution
- Add some feedback in both the position card and trade panel that an order is currently pending to deter users from submitting another trade.
- Disable close button when order is pending

_Designs pending ..._

**Comment by asherism** [comment]
> Disable close button when order is pending


good solution - i would also add a spinner to the order/modify button 
![image](https://user-images.githubusercontent.com/11524787/223008098-5978efab-7f72-42b6-ab5d-d21eea4cfac8.png)

**Comment by avclarke** [comment]
@asherism I think a spinner might be a bit confusing in this case as the transaction would have completed and it might just feel stuck with no other feedback. So maybe we disable the button instead and change the text to "Order pending" or something?

**Comment by asherism** [comment]
> @asherism I think a spinner might be a bit confusing in this case as the transaction would have completed and it might just feel stuck with no other feedback. So maybe we disable the button instead and change the text to "Order pending" or something?

yeah maybe we actually replace both buttons with something like this: 
<img width="349" alt="image" src="https://user-images.githubusercontent.com/11524787/223612147-fbcd6a32-7257-4041-b944-17a2cef1761a.png">
