### ISSUE TITLE
CM v2: Support both Isolated and SM on UI

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#2102]
### Subject of the issue
- Work out UI design to (temporarily) support isolated margin (legacy) and SM 
- Default to Smart Margin
- Make sure UI makes it clear legacy is not the premier option
- On Isolated, make clear it's legacy and inform users of the benefits of SM
- Make it clear trading rewards are only provided for SM
- Offer a path to migrate
- tbd

**Comment by avclarke** [comment]
<img width="1078" alt="Screenshot 2023-03-22 at 13 32 16" src="https://user-images.githubusercontent.com/3802342/226921496-db99583d-adc4-4e89-a20d-5df12e9b8cde.png">
<img width="1077" alt="Screenshot 2023-03-22 at 13 32 04" src="https://user-images.githubusercontent.com/3802342/226921503-d41de022-0525-4894-b97e-e6029e5154fa.png">
