### ISSUE TITLE
UI Refresh: Implement funding chart

### ISSUE THREAD

**Issue by avclarke** [Kwenta/kwenta#2144]
### Description

- Add a toggle in the market details bar to switch between price and funding chart
- Implement funding history chart similar to the portfolio chart
- Can construct the chart data from fundingRateUpdates query from the subgraph
- The chart should show the past weeks data with rates per hour

![image](https://github.com/Kwenta/kwenta/assets/4819006/e54cf039-e726-4c90-ad98-ebdfbbc29586)

Ref: [Figma Design](https://www.figma.com/file/YWU3PMsnqZaqr1gABgAFJK/UI-Refresh?type=design&node-id=8493-ref47034&t=ZnQij0qhBHA44JgA-4)

**Comment by platschi** [comment]
See also #1161

**Comment by koredefashokun** [comment]
@avclarke The Figma link above seems to not work correctly anymore. Would appreciate if you could send a new one or update it.
