### ISSUE TITLE
Mobile Refresh: Implement new market mobile nav and page structure

### ISSUE THREAD

**Issue by avclarke** [Kwenta/kwenta#2147]
### Description

Implement the updated mobile UI designs for the market page:

- [x] Fixed bar at the top containing balance, market and menu
- [x] Fixed bar at the bottom with buy / sell buttons and fees when trade panel open
- [x] Top navigation to switch between `price, trades, funding and stats`
- [x] Bottom user navigation `positions, Orders, Transfers, Trades`
- [x] Tapping the menu hamburger icon opens the menu and replaces the bottom bar with wallet / network buttons

**Comment by platschi** [comment]
Together with #2186
