### ISSUE TITLE
UI Refresh: Implement funding rate time period toggle

### ISSUE THREAD

**Issue by avclarke** [Kwenta/kwenta#2148]
### Description

Allow the user to select from a drop down the time period they wish to view funding rate for

<img width="172" alt="Screenshot 2023-04-03 at 14 14 22" src="https://user-images.githubusercontent.com/3802342/229520443-5976929b-dc2f-4918-89bf-b8b3fde4e211.png">

**Comment by platschi** [comment]
![Image](https://github.com/Kwenta/kwenta/assets/548702/b50caad6-c610-43f7-b1cd-5c76ad6f015e)
