### ISSUE TITLE
UX Bug: Display unavailable funds in closed markets

### ISSUE THREAD

**Issue by avclarke** [Kwenta/kwenta#2284]
### Subject of the issue
Currently when a market is closed there is no way to see how much funds are available from that market, since we filtered out closed markets from idle margin.

### Proposed solution
We should find somewhere to display idle margin in closed markets.

**Comment by asherism** [comment]
![Image](https://github.com/Kwenta/kwenta/assets/11524787/d9b8b15b-6a22-40af-ae73-564905afa49e)

https://www.figma.com/file/YWU3PMsnqZaqr1gABgAFJK/UI-Refresh?type=design&node-id=9260-75392&t=pW7PNxmIGtBYqo5W-4

**Comment by asherism** [comment]
maybe put them back in idle margin with a 'closed' market badge?

**Comment by avclarke** [comment]
@asherism I wonder if we should also have something on the available margin section of the market page, as right now I think it is concerning when a user opens that page to see their available margin 0 because it's locked in a closed market.

**Comment by platschi** [comment]
@asherism @avclarke  can you finish this one up/get to a conclusion? :)

**Comment by asherism** [comment]
desktop: 

![Image](https://github.com/Kwenta/kwenta/assets/11524787/b9be82ad-4eba-4d10-9ff3-1949ff093a91)

https://www.figma.com/file/YWU3PMsnqZaqr1gABgAFJK/UI-Refresh?type=design&node-id=9362-57216&t=OCLHP5omMbthWXPx-4

mobile:


![Image](https://github.com/Kwenta/kwenta/assets/11524787/99539cba-25d7-4e3d-b00f-797b9ec31324)

https://www.figma.com/file/YWU3PMsnqZaqr1gABgAFJK/UI-Refresh?type=design&node-id=9416-61921&t=OCLHP5omMbthWXPx-4

**Comment by avclarke** [comment]
@LeifuChen locked margin needs to be calculated from remaining margin in closed markets with no positions open.
