### ISSUE TITLE
Deploy futures subgraph to Kwenta subgraphs

### ISSUE THREAD

**Issue by JChiaramonte7** [Kwenta/kwenta#229]
https://github.com/Synthetixio/synthetix-subgraph/pull/124/files

Deliverables
---
- [x] Deploy subgraph
- [x] Get testnet sUSD
- [x] Make sure that we have contract created events in our subgraph

**Comment by kmeraz** [comment]
https://thegraph.com/hosted-service/subgraph/kmeraz/optimism-kovan-futures
