### ISSUE TITLE
Investigate event for depositing into futures contracts

### ISSUE THREAD

**Issue by JChiaramonte7** [Kwenta/kwenta#230]
Deliverables
---
- [ ] Find out if there are deposit/withdrawal events from the contract
- [ ] Find out if we are tracking these events in our current subgraph

**Comment by kmeraz** [comment]
Looks like the events do exist, but we are not currently tracking them in the subgraph.

This looks like it's the contract function for depositing/withdrawing - a negative input denotes a withdrawal, while a positive input denotes a deposit.
https://github.com/Synthetixio/synthetix/pull/1450/files#diff-d7a9e293947abe7ae18975f66df8e0e92fef2f229b6487287fd0399dc7e63788R860

The resulting event emitting function invoked:
https://github.com/Synthetixio/synthetix/pull/1450/files#diff-d7a9e293947abe7ae18975f66df8e0e92fef2f229b6487287fd0399dc7e63788R1079

The actual event:
https://github.com/Synthetixio/synthetix/pull/1450/files#diff-d7a9e293947abe7ae18975f66df8e0e92fef2f229b6487287fd0399dc7e63788R1076

So:
 - [x] Find out if there are deposit/withdrawal events from the contract
   - Need to confirm via testing, but looks like there are
 - [x] Find out if we are tracking these events in our current subgraph
   - We are not, but should be relatively straightforward
