### ISSUE TITLE
Smart Margin Conditional Orders Warning

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#2321]
### Subject of the issue

- [ ] Add message on degraded performance to Status bar System Status (optional: #2114 ) 
- [ ] Add warning that SL/TP orders in experimental mode and given network conditions can make the execution fail (design pending)

Option: Disable cond. orders confirm/edit buttons temporarily. Caveat existing conditions orders of users should be able to be edited.

**Comment by asherism** [comment]
![Image](https://user-images.githubusercontent.com/11524787/236966783-46ebbbef-0535-4b1b-a492-3a3396ddec4f.png)

**Comment by asherism** [comment]
should be just disabled imo

**Comment by avclarke** [comment]
@asherism I think if we continue with the warning it should be much more prominent, like with an acknowledge button before showing the inputs. We'll also need something on the Trade panel for limit / stop (not just SL / TP) and also the SL / TP modal.

**Comment by asherism** [comment]
https://www.figma.com/file/YWU3PMsnqZaqr1gABgAFJK/UI-Refresh?type=design&node-id=9254-70111&t=BIPU2P0znUnfis0h-4

**Comment by asherism** [comment]
![image](https://github.com/Kwenta/kwenta/assets/11524787/eb3506c9-1a8b-460e-aadc-a4fabdf15872)
