### ISSUE TITLE
UX Bug: Tablet and small laptop screen sizes 

### ISSUE THREAD

**Issue by avclarke** [Kwenta/kwenta#2375]
### Description

Currently the smallest desktop view before breaking into mobile:
<img width="781" alt="Screenshot 2023-05-23 at 19 49 41" src="https://github.com/Kwenta/kwenta/assets/3802342/682c9e9b-c767-4366-87a3-d2537fd030e6">

Small laptop size to focus on:
<img width="1072" alt="Screenshot 2023-05-23 at 19 48 11" src="https://github.com/Kwenta/kwenta/assets/3802342/f043bf66-be59-4458-820c-e6ea7fef0998">

Tablet size design considerations:
- Disable and hide history completely
- Design another layout between mobile and desktop
- Increase mobile break point
- Allow to scroll whole chart / positions column rather than within only positions section
- Revise positions table layout to two rows

**Comment by platschi** [comment]
Will be done together with #2259
