### ISSUE TITLE
UI: Add a line marking 0% on Funding Chart

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#2400]
### Subject of the issue
Community members suggested to add a line at 0% to make the Funding Chart look less 'naked'.

### Deliverables
- Design horizontal line on Funding Chart for 0% value
- Implement horizontal line based on design

**Comment by asherism** [comment]
![Image](https://github.com/Kwenta/kwenta/assets/11524787/4378e3ce-9c90-4835-92e4-40d46988e300)

same grey that is already being used on light/dark mode
