### ISSUE TITLE
Liquidity Mining Designs

### ISSUE THREAD

**Issue by JChiaramonte7** [Kwenta/kwenta#248]
Two rounds. 1 week rewards. 4 week rewards.

Deliverables
---
- [x] Dashboard Earnings
- [x] Page for Rewards
- [x] 3 hour countdown timer
- [x] Link to Synthetix Staking
- [x] Visualization showing two rounds
- [x] How much you've earned 
- [x] How much you have staked
- [x] Kwenta Rewards emission rate
- [x] Show info regarding rewards program

**Comment by asherism** [comment]
https://www.figma.com/file/YWU3PMsnqZaqr1gABgAFJK/UI-Refresh?node-id=1081%3A4938

**Comment by asherism** [comment]
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/11524787/152876100-182ebd88-9834-415c-a58f-be6926062ab4.png">
