### ISSUE TITLE
Synth onramp exchange rate incorrect for USDC, USDT

### ISSUE THREAD

**Issue by JChiaramonte7** [Kwenta/kwenta#25]
### Summary
The exchange rate for some tokens on the synth-onramp is incorrect. This seems to only be the issue for ERC20 tokens with 6 decimals (ie. USDC, USDT) so my hypothesis is that somewhere in the either Kwenta or `@synthetixio/queries` we are not accounting for this.

![image](https://user-images.githubusercontent.com/4015977/132387349-6a8a51b8-8c3d-497d-a1ea-ec5f49c17a40.png)

### Your environment
* L1 Mainnet
* Chrome - latest

### Expected behaviour
Factor in number of decimals when calculating an output amount from given input currency. (If hypothesis is correct)

### Actual behaviour
Currently doesn't consider decimals of input currency. (If hypothesis is correct)

### Steps to reproduce
1. Visit synth onramp
2. Select USDC or USDT (must be in wallet balance) as the quote currency

**Comment by ZanePseudo** [comment]
Found the issue. When getting a quote from 1inch, the currency decimals wasn't being used so it was defaulting to 18. Obviously, that works in most cases but as @JChiaramonte7 mentioned, it didn't for USDC/USDT.

**Comment by Admiral-REK** [comment]
Came to the same conclusion @ZanePseudo.  Suggested fix is now open for review.
