### ISSUE TITLE
🐛 Fix SHIB 24hr change

### ISSUE THREAD

**Issue by avclarke** [Kwenta/kwenta#2581]
### Description

SHIB is displaying a large number for 24hr change probably due to it's decimals changing.

We need to finish deploying the fix in the below PR on subgraph to handle these change correctly moving froward. 

https://github.com/Kwenta/kwenta-subgraph/pull/149

**Comment by Marko-roy** [comment]
![image](https://github.com/Kwenta/kwenta/assets/90076964/e5dc1144-7c7a-4b92-bb86-e7b446683505)
