### ISSUE TITLE
Design dynamic fees

### ISSUE THREAD

**Issue by JChiaramonte7** [Kwenta/kwenta#263]
Deliverables
---
- [x] Show dynamic fee next to current base fee in UI
- [x] "i" tooltip when dynamic fee is in effect

**Comment by asherism** [comment]
https://www.figma.com/file/sghReDviy1lcr6kkNqlc0e/?node-id=6120%3A230761

link to figma

**Comment by asherism** [comment]
![image](https://user-images.githubusercontent.com/11524787/150606684-eab23288-f0cb-4cf9-9c32-d8990de09aa2.png)
![image](https://user-images.githubusercontent.com/11524787/150606695-a285aaf6-8bc6-4ba6-bae5-82e0058e56f4.png)
