### ISSUE TITLE
:bug: OP Rewards Estimates Not Updating

### ISSUE THREAD

**Issue by Marko-roy** [Kwenta/kwenta#2635]
### Subject of the issue
Kwenta displays OP rewards in real-time as they are accrued, this seems broken currently. 

### Your environment
Chrome/Brave

### Expected behavior
Update Rewards after a trade is placed

### Actual behaviour
Static number of 0

### Steps to reproduce
Trade on Kwenta

<img width="259" alt="Screenshot 2023-07-21 at 11 41 58 AM" src="https://github.com/Kwenta/kwenta/assets/90076964/f06d3eaf-e44e-46f7-8777-75c14631d557">

**Comment by LeifuChen** [comment]
#2641
