### ISSUE TITLE
Design header component

### ISSUE THREAD

**Issue by JChiaramonte7** [Kwenta/kwenta#269]
Deliverables
---
- [x] Design palette H1-H6

**Comment by asherism** [comment]
https://www.figma.com/file/MFubYVZamMnSTLa70QSCdd/?node-id=0%3A1

**Comment by asherism** [comment]
![image](https://user-images.githubusercontent.com/11524787/151678308-6fb0fb0c-0300-4fc5-aa2e-76c48a90c361.png)
