### ISSUE TITLE
Leaderboard: MKR icon not loading correctly

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#2726]
### Subject of the issue
Checking a random wallet with a MKR trade, the icon does not load:

<img width="356" alt="Screenshot 2023-08-01 at 21 45 33" src="https://github.com/Kwenta/kwenta/assets/548702/4f31089f-0237-495e-a2e0-9e3752b41686">

Everywhere else it does load correctly, however.

**Comment by LeifuChen** [comment]
test wallet: 0x614B7de7A18839489e587157D4a44e939a1bfbe7
<img width="1101" alt="截屏2023-08-02 10 51 54" src="https://github.com/Kwenta/kwenta/assets/4819006/0ed66df2-bf26-45d0-8c0a-8e141953d092">
