### ISSUE TITLE
Swap Designs

### ISSUE THREAD

**Issue by asherism** [Kwenta/kwenta#276]
Deliverables
---
- [x] Advanced/Basic toggle
- [x] Implement designs from wireframe
- [ ] Implement mobile designs

**Comment by asherism** [comment]
update simple swap and add toggle

**Comment by asherism** [comment]
simple mode:
https://www.figma.com/file/YWU3PMsnqZaqr1gABgAFJK/UI-Refresh?node-id=1773%3A10888

advanced mode: 
https://www.figma.com/file/YWU3PMsnqZaqr1gABgAFJK/UI-Refresh?node-id=1846%3A9749

**Comment by platschi** [comment]
Up to date design can be found in #452
