### ISSUE TITLE
GetL2GasCard MessageButton text outdated

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#282]
### Subject of the issue
Kwenta prompts users to buy wETH when on L2

### Your environment
* Optimism
* FIrefox latest

### Expected behaviour
Kwenta should prompt users to "bridge ETH"

### Actual behaviour
Prompt text is correct, but message button prompts "buy wETH"

### Steps to reproduce
- Visit https://kwenta.io/exchange/sETH-sUSD on Ethereum Mainnet
- Switch to Optimism Mainnet

Note that when visiting with Kwenta with Optimism as default network, the UI instead shows ``Your wallet has no Synths. Mint sUSD on Staking to trade Synths:``. Switch networks forth and back to have the `buy ETH` notification appear.

Make sure consistent use of the wording 'ETH' is used, instead of 'wETH'.

### Relevant Code: 

https://github.com/Kwenta/kwenta/blob/10f59cd74aff8f556bc5658103bb7e84493a8db2/sections/exchange/FooterCard/GetL2GasCard/GetL2GasCard.tsx#L35-L36

https://github.com/Kwenta/kwenta/blob/4c79af8a23373811e6fa7c50c4cc824c72d0e84b/translations/en.json#L640

![Screenshot 2022-01-22 at 16-23-05 Kwenta](https://user-images.githubusercontent.com/548702/150652944-972e300c-c772-4c43-b217-c111563f26cc.png)

### Reward

25 SNX

**Comment by sudiptobera** [comment]
![Screenshot (111)](https://user-images.githubusercontent.com/83639486/151227695-a4f9c20b-10a0-428f-ade8-a66418b2b743.png)

**Comment by sudiptobera** [comment]
working fine

**Comment by platschi** [comment]
Assigned to @Burtrico

**Comment by platschi** [comment]
Assigned to @LeifuChen
