### ISSUE TITLE
Tally wallet integration

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#291]
### Feature Proposal
Integrate [Tally wallet](https://tally.cash) as an option into the 'Select Wallet' modal on Kwenta.

### Rationale
Tally is an upcoming community-owned wallet with quite some traction within the community. Currently in alpha status.

### Implementation
- Instructions: https://docs.tally.cash/tally/developers/integrating-dapps
- Upgrade `bnc-onboard` to `1.36.0` (make sure to use the exact version)
- Add Tally as a wallet option in our onboard config
- Config and test thoroughly

### Relevant Code

https://github.com/Kwenta/kwenta/blob/069c097e7dec4b695eb3f2c5f803b81c5612a27a/containers/Connector/config.ts#L18-L67

### Reward

50 SNX

**Comment by LeifuChen** [comment]
@platschi Can I pick this ticket?

**Comment by platschi** [comment]
Assigned to @Kethcode
