### ISSUE TITLE
Settle fee reclamations if >12 trades

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#321]
### Subject of the issue
There is an edge case situation on L1 when a trader trades 12 consecutive trades into a specific synth, the trader needs to settle the rebate in order to be able to trade a 13th attempt. The system will automatically disallow any further trading attempts if the trader does not settle. Currently the Kwenta UI leaves the trader in the dark might this situation kick in.

More information see [SIP-37](https://sips.synthetix.io/sips/sip-37) and [Kwenta Docs](https://docs.kwenta.io/resources/fee-reclamation).

See also for more information on the bug report [this Discord conversation](https://discord.com/channels/852273007370960937/852530414287454278/933826672313127013).

### Proposed solution
 - Instead of displaying our usual trade submission section, the interface should show a message and ask the trader to settle. 
 
The logic here requires a query to `Exchanger.settlementOwing` with the traders address and output synth to retrieve the `numEntries`. If `numEntries >= 12` require the trader to settle.

- Example message: `You have 12 consecutive trades into <SYNTH_NAME_HERE>. Please trade out of <SYNTH_NAME_HERE> or settle: (Settle Button)`.
- Add a "Learn more" link sending the trader to [this](https://docs.kwenta.io/resources/fee-reclamation) Kwenta Docs article

The format should be similar to the `NoSynthsCard`. Design mockup example:

![rebate_design](https://user-images.githubusercontent.com/548702/152077051-fd88304c-b790-442d-acf4-d2ac8522f54c.png)

### Steps to reproduce
- On L1 Kovan, trade into the same synth 12 times in order to test this issue.

### Rewards
75 SNX

**Comment by platschi** [comment]
Assigned to @kethcode

**Comment by kethcode** [comment]
I've made some work on this.  feel free to use some or none of it.  https://github.com/kethcode/kwenta/tree/fix/settle_consecutive_trades
