### ISSUE TITLE
Implement Leaderboard

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#326]
### Description
Implement the leaderboard and have traders listed in ranking based on Total Profit & Loss (PnL). 

See issue #278 for the leaderboard design

### Deliverables
- [ ] Final PR to `v2` branch
- [ ] Connect the leaderboard to current subgraph: https://thegraph.com/hosted-service/subgraph/kmeraz/optimism-kovan-futures
- [ ] Pull PnL using `pnlWithFeesPaid` from the subgraph
- [ ] Fill out the leaderboard with any traders who have PnL
- [ ] Display liquidations
- [ ] Display total trades placed
- [ ] Add timeframe buttons, as seen in the designs. (does not have to be functional yet)
- [ ] Use addresses instead of twitter handles for the "Trader" column

### Notes
- Currently there should only be one user who has interacted with the futures contracts
- Layout and background colors will be done in a future ticket
- PnL by selected timeframe will be done in a future ticket (but bonus points for ideas for how to solve this)

### Rewards
50 SNX

**Comment by platschi** [comment]
Assigned to @tburm

**Comment by Tburm** [comment]
@platschi I submitted a PR [here](https://github.com/Kwenta/kwenta/pull/340)

There is one outstanding issue related to linting that I would like to get some feedback from a CC if possible.
