### ISSUE TITLE
Earn UI

### ISSUE THREAD

**Issue by JChiaramonte7** [Kwenta/kwenta#334]
Deliverables
---
- [x] Add "earn" section to `V2`
- [x] SNX staking rewards section
- [x] Curve pool rewards sections
- [x] "Liquidity Mining Program" for SNX staking rewards
- [x] "sUSD-DAI CURVE LP" for curve rewards
- [x] Descriptions for each program
- [x] Timer in UI
- [x] Rewards calculation and disabled claim button

**Comment by platschi** [comment]
Relevant branch: https://github.com/Kwenta/kwenta/tree/earn-page
