### ISSUE TITLE
Shorting: Accrued Interest amount too long

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#349]
### Subject of the issue
When [Shorting](https://kwenta.io/shorting) synths on Kwenta, the **Accrued Interest** amount in the "Your Positions" table exceeds the limits of the table for a value of 0. See screenshot below.

### Your environment
* Optimism
* Firefox

### Steps to reproduce
- Visit Kwenta Optimistic Kovan for testing purposes
- Short an asset. Given current total longs outweigh the shorts, accrued interest should be 0.

### Deliverables
- [ ] Make sure accrued interest amount is shown with a maximum of 4 decimals.

### Reward
25 SNX

![Screenshot 2022-02-15 at 12-21-28 Kwenta](https://user-images.githubusercontent.com/548702/154094514-e30789b8-730d-495d-8a9f-d9c0a58ece76.png)

**Comment by joeyfigaro** [comment]
Taking a look at this.

**Comment by joeyfigaro** [comment]
@platschi can you confirm for me that you guys are using `Node v14.17.1` and `NPM 6.14.13`? Seeing some warnings during dependency install and native/node-gyp build failures.

**Comment by LeifuChen** [comment]
> @platschi can you confirm for me that you guys are using `Node v14.17.1` and `NPM 6.14.13`? Seeing some warnings during dependency install and native/node-gyp build failures.
> 
> > npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

Please contact @platschi in Kwenta discord #community-dev if you want to pick the ticket.
platschi recommended using npm 8.4.1 and node v16.13.2

**Comment by alcipir** [comment]
https://github.com/Kwenta/kwenta/blob/58671609bbfe2c22b6a636db64df7fc2c79d553a/sections/shorting/ManageShort/PositionCard.tsx#L304

wouldn't adding a maxDecimals: 4 option after currencyKey do the trick? @joeyfigaro

**Comment by LeifuChen** [comment]
> https://github.com/Kwenta/kwenta/blob/58671609bbfe2c22b6a636db64df7fc2c79d553a/sections/shorting/ManageShort/PositionCard.tsx#L304
> 
> wouldn't adding a maxDecimals: 4 option after currencyKey do the trick? @joeyfigaro

It's a column inside shorting history table. So you may want to check here https://github.com/Kwenta/kwenta/blob/58671609bbfe2c22b6a636db64df7fc2c79d553a/sections/shorting/ShortingHistory/ShortingHistoryTable/AccruedInterestCol.tsx#L31

Again please contact  @platschi in Kwenta discord #community-dev if any of you wants to pick this ticket.

**Comment by alcipir** [comment]
alright! @joeyfigaro seems to be on it already. 

I was just curious if that was the case, but didn't want to get ahead of the line.

**Comment by kethcode** [comment]
make sure to get into discord and claim it.  claim first, start work second.  otherwise, we get into claim wars.

**Comment by platschi** [comment]
Hey everyone, happy to see you're all interested in helping out with the devDAO! Please join our Discord (https://discord.gg/kwenta) and claim tickets there, as kethcode pointed out we have a system set up, otherwise we'll be fighting over tickets in different places :) Thanks!

**Comment by alcipir** [comment]
Thanks guys :) 
Just to be clear, not my intention to claim this one, sorry if that seemed like the case.

**Comment by platschi** [comment]
Assigned to @WillkommtomyGithub

**Comment by joeyfigaro** [comment]
> https://github.com/Kwenta/kwenta/blob/58671609bbfe2c22b6a636db64df7fc2c79d553a/sections/shorting/ManageShort/PositionCard.tsx#L304
> 
> wouldn't adding a maxDecimals: 4 option after currencyKey do the trick? @joeyfigaro

That's what I was thinking, yeah! 

I ended up catching a notification for this issue via Twitter, so I came in sideways. I've been watching Kwenta for a while though, and look forward to helping out with future issues that are good for first time contributors. :) See you all in Discord.
