### ISSUE TITLE
Dynamic shortable asset list

### ISSUE THREAD

**Issue by JChiaramonte7** [Kwenta/kwenta#359]
### Feature Proposal
Generate shortable asset list for each network.  

### Rationale
Currently the shortable synth asset list is hardcoded.
https://github.com/Kwenta/kwenta/blob/e84be821ca0db2ecaaf4a53221eb380b4752ea06/sections/shorting/constants.ts#L3-L4

### Implementation
- Look at the current list of synths and check if each asset is short-able with `CollateralManager.shortableSynthsByKey(CURRENCY_KEY)` which returns non-zero if the asset is shortable. 
-   Completely replace `SYNTHS_TO_SHORT` and `SYNTHS_TO_SHORT_L1`
- Use [multicall](https://github.com/Destiner/ethcall) to batch the calls.

### Rewards
150 SNX

**Comment by platschi** [comment]
Assigned to @kethcode

**Comment by kethcode** [comment]
CollateralManager.shortableSynthsByKey isn't available on the L1 contract. I'm going to leave the L1 list hardcoded, since L1 shorts are deprecated anyway.

**Comment by kethcode** [comment]
Ok, I've got an alternate approach for the L1 that will handle replacing it fine.

**Comment by kethcode** [comment]
Here's you're hook.  I can't seem to navigate the async, so I'm done.  Give it to someone else.

	import { CurrencyKey, Synths } from 'constants/currency';
import Connector from 'containers/Connector';
import { ethers } from 'ethers';

export const getSynthShortList = async () => {
	const { synthetixjs } = Connector.useContainer();
	let SYNTHS_TO_SHORT_L1 = [Synths.sBTC, Synths.sETH, Synths.sLINK];
	let SYNTHS_TO_SHORT: CurrencyKey[] = [];

	for(var synth in Synths) {
		var retval = parseInt(await synthetixjs!.contracts.CollateralManager.shortableSynthsByKey(ethers.utils.formatBytes32String(synth)))
		if(retval > 0)
		{
			SYNTHS_TO_SHORT.push(synth as CurrencyKey)
		}
	}

	console.log("SYNTHS_TO_SHORT:", SYNTHS_TO_SHORT)

	return { SYNTHS_TO_SHORT_L1, SYNTHS_TO_SHORT };

};
