### ISSUE TITLE
Synthetix/Kwenta build IDs on UI

### ISSUE THREAD

**Issue by JChiaramonte7** [Kwenta/kwenta#36]
## Feature Proposal
We should add build IDs to the bottom of the Kwenta page to help us as the community narrow down help-desk issues. This can be either tied to a Kwenta commit hash or [Synthetix version](https://github.com/Synthetixio/synthetix/releases). Or both.

### Rationale
Someone posts an issue to the help-desk and we inquire which version of Kwenta they're on. 

Having a build ID that links us to either a commit and/or Synthetix can help us eliminate potential causes. Typically issues arise because someone has an old build cached on their machine and the version of Synthetix is outdated. (Context: sometimes Synthetix contract addresses change with each deployment.)

### Implementation
- Some research has to be done into how to get commit hashes and/or Synthetix versions.
- Note: [@synthetixio/contracts-interfaces](https://www.npmjs.com/package/@synthetixio/contracts-interface) version is a good proxy to the Synthetix version and might have the granularity we want.

### Design Spec

Link to Figma (Hard to see, but small and at the bottom of the page):
https://www.figma.com/file/sghReDviy1lcr6kkNqlc0e/Kwenta-User-Flows?node-id=5267%3A228978

Screenshot from Figma:

![image](https://user-images.githubusercontent.com/4015977/132720453-3e3b54d8-da0c-456b-975c-7a9700064cee.png)

**Comment by ZanePseudo** [comment]
Sorry for the two PRs, first one couldn't get my verified commit working properly, but sorted out for the second one that's open
