### ISSUE TITLE
Integrate EIP-1559

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#361]
### Subject of the issue
Integrate EIP-1559 into Kwenta.

### Dependencies
PR #358 must be merged first

### Deliverables

- [ ] Refactor all instances of gas calculation into the `useGasPrice` hook:
   - `GasPriceSummaryItem`
    - `useExchange`
    - `ManageShortAction`
    - `ShortingRewards`
    - `useShort`
    - `useRedeemDeprecatedSynths`
    - `FeeReclaimingSynths`

- [ ] Making sure we use `maxPriorityFeePerGas` and `maxFeePerGas` on mainnet (EIP-1559), but continue to use `gasPrice` on every other network (best way to do this could be to refactor the `useGasPrice` hook to return an object)

### Useful Resources

- Cheatsheet: https://hackmd.io/@tvanepps/1559-wallets

### Rewards
300 SNX

**Comment by platschi** [comment]
Assigned to @burtrico

**Comment by brossetti1** [comment]
ok some follow ups as ive been researching this more today:

Mainnet
in regards to eip1559 - to me it looks like the synthetix version of maxFeePerGas is calculating the 1559 gas fees and incorporating the maxPriorityFee at the same time. Its using this formula: 

`baseFee * 2 + maxProrityFeePerGas`

this is the same formula that [blocknative uses](https://www.blocknative.com/gas-estimator) for its [gas-estimator which is 1559 compliant](https://www.blocknative.com/blog/eip-1559-fees#:~:text=Our%20EIP%2D1559%2Dcompliant%20Gas,Base%20Fee%20)%20%2B%20Max%20Priority%20Fee
)

[here is where the useEthGasPriceQuery](https://github.com/Synthetixio/js-monorepo/blob/master/packages/queries/src/queries/network/useEthGasPriceQuery.ts#L14 ) is doing this calculation already

to me this looks like 1559 is already being used on mainnet and `parseGasPriceObject` is rightfully calling `maxFeePerGas`

1) can we confirm thats the case?


Optimism
on Optimsim, there is no base fee, as mentioned in the [optimism fee docs](
https://community.optimism.io/docs/developers/build/differences/#opcode-differences)

there are calculations and a price oracle for the [L1 transaction](
https://community.optimism.io/docs/developers/build/transaction-fees/#understanding-the-basics)

Kwenta already has the [priceOracle implemented here](
https://github.com/Kwenta/kwenta/blob/master/hooks/useGetL1SecurityGasFee.tsx#L25)

2) I am still confused how 1559 can be worked into optimism and Kwenta but I am wondering if the purpose of the ticket has to do with calculating the limit and L1fee into the `useGas` hook?

as I see it currently, you cant technically implement 1559 on optimism and on mainnet, synthetix is already implementing a for of calculating the fees for 1559 by passing us `maxFeePerGas (baseFee * 2 + maxProrityFeePerGas)` and maxPriorityFee is already accounted for here.

still trying to orient what I need to do next but to me this ticket seems like its really just refactoring gas oriented logic into `useGas`, anyway I can get a better description of the steps to take for bullet point 2? 

@JChiaramonte7 may know how to expand on this more?

**Comment by platschi** [comment]
@JChiaramonte7 ☝️

**Comment by JChiaramonte7** [comment]
@brossetti1  

`useEthGasPriceQuery` already returns a mostly proper object with three fields that can already be passed into a transaction
```
{ 
    maxPriorityFeePerGas, // needed by 1559
    maxFeePerGas, // needed by 1559
    baseFeePerGas, // not necessary 
    gasPrice // needed for all networks other than ethereum mainnet
}
```
[`GasPrice` Object](https://github.com/Synthetixio/js-monorepo/blob/fab6538b72813dce47018a3f2d9a31e0af0cf44c/packages/queries/src/types.ts#L5-L10)

And to be clear there is no EIP-1559 on optimism mainnet (so you have to use `gasPrice`)

> @JChiaramonte7 may know how to expand on this more? https://github.com/Kwenta/kwenta/blob/347ada41857cd524412923df58e0c4423df0c862/hooks/useGas.ts#L10-L20

This was just a **temporary** patch fix to make responses from `useEthGasPriceQuery` work in Kwenta by falling back on the legacy transaction submission mechanism. This function will either return `gasPrice`, if it exists, or `maxFeePerGas` from the `GasPrice` object that is returned from `useEthGasPriceQuery`. 

This returned number is then eventually used in the [`gasPrice`](https://docs.ethers.io/v5/api/utils/transactions/#Transaction) field when submitting a transaction.

**Comment by JChiaramonte7** [comment]
Addendum for deliverable # 2. Note this is just my high level suggestion and there could be a better way to do this.

- After refactoring everything into `useGas` make the hook return either an object with 
```
{
    maxPriorityFeePerGas,
    maxFeePerGas
}
```
for eip-1559 networks

or
```
{
    gasPrice
}
```
for everything else.

**Comment by brossetti1** [comment]
@platschi @JChiaramonte7 thanks for all that detail, really helpful here. I have been working on this some more this afternoon and am currently feeding `useExchange` transactions with 1559 compliant fees.

![Screen Shot 2022-03-01 at 6 08 33 PM](https://user-images.githubusercontent.com/5998100/156278169-20377b01-d144-4cbd-990a-93c6b47b2acf.png)
![Screen Shot 2022-03-01 at 6 12 34 PM](https://user-images.githubusercontent.com/5998100/156278171-c7d66626-fa91-4ee1-995c-c9cece7b7597.png)

I can also see now that `useEthGasPriceQuery` is doing a general 1559 compliant fee structure but it falls short of a good estimate of fees based on history. I really [MyCrypto's implementation of this fee estimate](https://github.com/MyCryptoHQ/MyCrypto/blob/master/src/services/ApiService/Gas/eip1559.ts) and my next step will be to implement a similar algorithm for returning the `maxPriorityFeePerGas` and `maxFeePerGas` values. 

some things that I am worried about right now:

 I have been refactoring other gas related functionality im seeing in these components into `useGas`. I am hoping this is ok for the story, right now the `useGas` looks like this:

```
const useGas = () => {
  ...
  
  return {
    gasPrice,
    gasPriceWei,
    getGasLimitEstimate,
    maxFeePerGas,
    maxPriorityFeePerGas,
    gasPrices,
    gasSpeed,
    setGasSpeed,
    isCustomGasPrice,
    customGasPrice,
    setCustomGasPrice,
    gasConfig,
  };
}
```

where `gasConfig` is the required object that can be spread into the [gas settings of a transactions](https://github.com/Kwenta/kwenta/pull/377/files#diff-775118eccd3373aaed2a2ec3d37976b257a4fea20f41dc649d70b962b253674dR729), replacing `{ gasPrice: gasPriceInWei }` for the dynamic structure based on [L1 vs L2 you referenced above](https://github.com/Kwenta/kwenta/issues/361#issuecomment-1054846840).

1) can we confirm that we want a more detailed values for eip1559 transactions as seen in the MyCrypto reference above?

or is that passed the scope of this ticket?

2) more of a statement, Ill continue with my current solution until I have flushed it out for all components, it looks like shorts are not available on L1 which makes things alot easier, if you're glancing at the [associated WIP Draft] and happen upon anything that seems overly complicated, unnecessary, or improperly implemented, feel free to leave a comment. (maybe more for @platschi - early review of sorts)

ill continue on this one tomorrow when I have time.
