### ISSUE TITLE
hype site 2 of 6

### ISSUE THREAD

**Issue by asherism** [Kwenta/kwenta#369]
- [x] Design it (high fidelity)
- [x] Implement it

**Comment by asherism** [comment]
https://www.figma.com/file/YWU3PMsnqZaqr1gABgAFJK/UI-Refresh?node-id=1782%3A9477

**Comment by asherism** [comment]
<img width="841" alt="image" src="https://user-images.githubusercontent.com/11524787/158649309-3dce85b8-f395-4f2f-b38a-464a54e934e2.png">

**Comment by platschi** [comment]
Implementation https://github.com/Kwenta/hype/issues/7
