### ISSUE TITLE
Visual padding issue with Synth Onramp and Shorts input boxes

### ISSUE THREAD

**Issue by JChiaramonte7** [Kwenta/kwenta#37]
### Subject of the issue
There is extra padding on the left of the "From" currency box. This is visible on the https://kwenta.io/dashboard/convert and https://kwenta.io/shorting pages. Find what caused this issue and see if a fix can be implemented without impacting other components (mobile and desktop view).

### Your environment
* Network used: All
* Which browser: Chrome - latest

### Expected behaviour
![image](https://user-images.githubusercontent.com/4015977/132722308-e0b731b4-26ff-4767-80e8-105b10a2e96f.png)

### Actual behaviour
![image](https://user-images.githubusercontent.com/4015977/132722366-58de89e2-13e2-45cd-9908-d328bbcf8ccd.png)

### Steps to reproduce
Visit https://kwenta.io/dashboard/convert and https://kwenta.io/shorting on desktop.

**Comment by platschi** [comment]
The "From" box uses the `.currency-card-quote .currency-card-body` padding added in commit https://github.com/Kwenta/kwenta/commit/243ea1fcc117a1f999af0c27057605f7bbf9450c , removing the `padding-left: 61px` eliminates the extra padding on desktop. Mobile is not affected.

https://github.com/Kwenta/kwenta/blob/79aaa53cf58647c7a8cdf10ba320c017d311ee76/styles/common.tsx#L397-L409
