### ISSUE TITLE
Tx History does not list new assets

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#410]
### Issue
On the dashboard transaction history, recently added synths are not listed in the 'To' column, making it difficult to distinguish trades.

Synths affected are: sEUR, sMATIC, sAVAX, sSOL

Related ticket #336 solved this issue for previously available synths.

![Screenshot 2022-03-16 at 11-10-36 Kwenta](https://user-images.githubusercontent.com/548702/158611102-d5d4b53c-232b-4c90-a0d3-d33852d71230.png)

### Steps to reproduce
- Visit https://kwenta.io
- Connect to Optimism Kovan
- Exchange sUSD to any of the above synths
- Check tx history after a few seconds

### Deliverables
- Make sure all synths are listed correctly in the respective column of the tx history
- Make sure future synth additions work automatically to avoid this bug popping up again.

### Rewards
25 SNX

**Comment by kethcode** [comment]
something fixed this in the alst couple days, and it wasn't me.  
![image](https://user-images.githubusercontent.com/94415863/159824627-d10b2b69-bd9f-4d1a-a187-a093ac23717d.png)
