### ISSUE TITLE
v2: Minimum margin requirement info

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#415]
### Subject of the issue
People may miss depositing margin, and be confused why nothing works, probably 0 margin should make every other action not available / display a notification on press.

The minimum margin needed to trade is $100. When depositing <100$ and/or having a margin <100$, the interface should show an information message regarding this fact.

### Temporary solution

- [x] disable place order button if margin below $100 and some sort of clear status message near it
- [x] display warning if depositing <100$

"Minimum margin to trade is 100$"

### Ideas:

- [x]  Show Info Box under 'Deposit' / Withdrawal boxes when Margin <100$
- [x] On Deposit Modal, show information message when (current margin + deposit input amount) <100$.

**Comment by asherism** [comment]
modal: 
https://www.figma.com/file/YWU3PMsnqZaqr1gABgAFJK/UI-Refresh?node-id=1925%3A10763
<img width="600" alt="image" src="https://user-images.githubusercontent.com/11524787/159590190-a1b2e55a-2557-4155-8b04-6479b0c390c2.png">

futures ui:
https://www.figma.com/file/YWU3PMsnqZaqr1gABgAFJK/UI-Refresh?node-id=1935%3A12431
<img width="468" alt="image" src="https://user-images.githubusercontent.com/11524787/159590269-83d0e756-793f-460a-b252-3dcae897d12a.png">
