### ISSUE TITLE
Show leverage on Dashboard Positions

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#416]
### Suggestion
Positions don’t show leverage so hard to know which position is close to being liquidated, also type of margin is unclear (is it deposited margin, accessible margin, or remaining margin)

- [x] Add Leverage Data Column
- [x] Replace Margin with Total Notional Size of Position
- [x] Leverage should show dash if value = 0.

Ticket #442 (Add Liquidation Price) touches the same table and could be done simultaneously by the dev.

![margin](https://user-images.githubusercontent.com/548702/158695535-9fccd3f2-51d7-49c1-9792-8f037e51440e.png)

**Comment by Tburm** [comment]
Totally agree with this one. At the very least we should display position size, potentially leverage as well.

Another suggestion is a way to flag positions that can be liquidated or are close to liquidation.
