### ISSUE TITLE
Unsupported Network

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#427]
Error when "connect wallet" while the wallet is connected to an unsupported network. Throws Unhandled Runtime Error

To reproduce:
- Refresh
- Set wallet to network like Polygon
- Connect wallet

## Deliverables
- [x] Design flow when connected to unsupported network

**Comment by asherism** [comment]
https://www.figma.com/file/YWU3PMsnqZaqr1gABgAFJK/UI-Refresh?node-id=1959%3A15788
<img width="1627" alt="image" src="https://user-images.githubusercontent.com/11524787/159797247-5cb0eb9f-7afc-4e05-baf7-15e262894b19.png">
