### ISSUE TITLE
Swap UI Implementation

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#452]
Implementing the new v2 Swap UI design into Kwenta. The Swap UI consists of two elements: The (basic) Synth Exchange and the Advanced Trading Mode.

### Purpose of the ticket
This ticket tracks the Swap UI implementation

### Deliverables

- [x] Implement new Synth Exchange design (basic)
- [x] Write unit test for new synth exchange

### Ticket Tracker

- #276

#### Basic Synth Exchange
- #459

**Comment by asherism** [comment]
advanced swap:
https://www.figma.com/file/YWU3PMsnqZaqr1gABgAFJK/UI-Refresh?node-id=1846%3A9749
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/11524787/159050705-bc473b7c-0508-463d-9662-0549b8d2577a.png">

simple swap:
https://www.figma.com/file/YWU3PMsnqZaqr1gABgAFJK/UI-Refresh?node-id=1885%3A16044
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/11524787/159050765-4f6f1506-5609-4adc-b204-651b5caad0cb.png">
