### ISSUE TITLE
Close Position Modal Improvements

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#495]
### Subject of the issue
The Close Position Modal uses an outdated golden PrimaryButton. It should update to match the button with other modals (primarily the Open/Modify Position modal).

Additionally, the synth symbol is currently shown in front of an amount, without a space between the synth symbol and amount. 

![Screen Shot 2022-03-28 at 15 44 38](https://user-images.githubusercontent.com/548702/160465535-0f1e7e9f-4ef8-4991-8a27-0f57ded9282f.png)

### Deliverables

- [ ] Update golden "Close Position" button to match design. See "Confirm Order" modal for the correct button layout.
- [ ] Move synth symbol (e.g. ETH) behind the amount, leave a white space between amount and symbol 

### Rewards
25 SNX

**Comment by benjabuidl** [comment]
![symbol](https://user-images.githubusercontent.com/101892440/161384764-dfafcd91-0135-477e-b368-a9578cbb0b81.png)
![seth](https://user-images.githubusercontent.com/101892440/161384765-959334e2-e76b-4760-9d89-e45838a0d8ad.png)

@platschi I should be using the synth symbol ( Ξ ) on the close modal right and not (sETH)? That's what I've seen in the confirm and modify modals for the size. 

I checked the bg colors and they were the same, the difference was the height.

**Comment by platschi** [comment]
> ![symbol](https://user-images.githubusercontent.com/101892440/161384764-dfafcd91-0135-477e-b368-a9578cbb0b81.png) ![seth](https://user-images.githubusercontent.com/101892440/161384765-959334e2-e76b-4760-9d89-e45838a0d8ad.png)
> 
> @platschi I should be using the synth symbol ( Ξ ) on the close modal right and not (sETH)? That's what I've seen in the confirm and modify modals for the size.
> 
> I checked the bg colors and they were the same, the difference was the height.

Hey benja, let's use "ETH", without the *s*.  Thanks!
