### ISSUE TITLE
"Refer" button doesn't work on main "Futures" page

### ISSUE THREAD

**Issue by drptbl** [Kwenta/kwenta#53]
### Subject of the issue
"Refer" button doesn't work on main "Futures" page:
https://kwenta-git-feat-futures-kwenta.vercel.app/futures

### Your environment
* Optimism Kovan
* Chrome v92.0.4515.159

### Screenshots
<img width="1058" alt="Screenshot 2021-09-16 at 00 21 35" src="https://user-images.githubusercontent.com/8177587/133517630-262cf92d-c8b8-46ea-8a6d-9c9a5a8aa1da.png">

**Comment by JChiaramonte7** [comment]
Closing because we're removing this page
