### ISSUE TITLE
Implement Stats page

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#545]
### Subject of the issue
Implement a responsive version (mobile / desktop) of the Kwenta Stats page.
### Design
https://www.figma.com/file/mcaXc01qAA1si3I8shXkeI/Kwenta---Website?node-id=1061%3A1350

### Deliverables

- [x] Add a "Stats" navigation link to the trading page (to the right of landing page)
- [x] Implement a responsive Stats page to cover both mobile and desktop layout as defined in design spec above. 

Add the follow Statistics (same as mockup):

- [x] Futures Trading Volume over time (/w filters 24h/1w/1m/max)
- [x] Total Trades / Trader by Period
- [x] Total Unique Traders / Traders by Period
- [ ] TVL per asset
- [x] Current Total Open Interest per asset 

### Notes
For more detailed questions, please contact the devDAO PM. All data can also be found on the Dune dashboard for reference.

### Deadline
August 11, 2022

### Rewards
500 SNX

**Comment by platschi** [comment]
#1485

**Comment by Tburm** [comment]
@platschi we should be able to close this one after the PR is merged. There is no `TVL` chart, but we don't have a TVL to display. Even with cross margin, sUSD on active positions is burned so we can't check contracts for deposited sUSD.
