### ISSUE TITLE
Changing currency on "Futures" page doesn't change a prefix before value (it's always a $)

### ISSUE THREAD

**Issue by drptbl** [Kwenta/kwenta#55]
### Subject of the issue
Changing currency on "Futures" page doesn't change a prefix before value (it's always a $).

### Reproduction steps:
1. Go to "sBTC Futures" page (https://kwenta-git-feat-futures-kwenta.vercel.app/futures/market/sBTC)
2. Connect your wallet
3. Click "Settings" icon located in top right corner
4. Change currency to "BTC" or "ETH" => values have changed on the website, but prefix is still a $

### Your environment
* Optimism Kovan
* Chrome v92.0.4515.159

### Screenshots
![2021-09-16 00 29 00](https://user-images.githubusercontent.com/8177587/133518497-a79fdab7-cfb4-4bb7-81a8-cbbac92b3655.gif)

**Comment by clementbalestrat** [comment]
Hmm problem is I don't see any benefit of using a different quote than sUSD for futures

**Comment by clementbalestrat** [comment]
I will let Kwenta decide what the best option is
