### ISSUE TITLE
Improve WalletOptionsModal

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#559]
### Subject of the issue
The `WalletOptionsModal` is not up to date with the new design. Make sure the layout is streamlined throughout Kwenta. The two options (Switch Wallet, Disconnect Wallet) should be shown in the same table style as the NetworkSwitcher modal.

### Desired layout
See Mockup below

### Deliverables
- [x] Update WalletOptionsModal dropdown layout to match that of NetworksSwitcher (see image)
- Dropdown Option 1: Switch Wallet
- Dropdown Option 2: Disconnect Wallet
- [x] Add Dropdown "Arrows"
- [x] Add Icons (see comment below)

### Rewards
50 SNX

**Comment by asherism** [comment]
<img width="843" alt="image" src="https://user-images.githubusercontent.com/11524787/160720042-5d1633ce-47ce-4743-8888-8abf34056d9d.png">

**Comment by asherism** [comment]
![Switch](https://user-images.githubusercontent.com/11524787/160720511-9e154939-f116-4cec-a326-0d601ee4f912.svg)
![Disconnect](https://user-images.githubusercontent.com/11524787/160720520-49d3c593-80a9-47c3-b4fd-136c04e50f38.svg)
