### ISSUE TITLE
PositionCard Design Revamp

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#563]

**Comment by asherism** [comment]
<img width="521" alt="image" src="https://user-images.githubusercontent.com/11524787/163269679-5a40c0c6-06a2-493e-8257-8081692f280f.png">

**Comment by asherism** [comment]
<img width="238" alt="image" src="https://user-images.githubusercontent.com/11524787/163269747-1ad186c8-a9a8-4f27-a748-1c4b2be39084.png">

**Comment by asherism** [comment]
https://www.figma.com/file/YWU3PMsnqZaqr1gABgAFJK/UI-Refresh?node-id=2535%3A26668
