### ISSUE TITLE
Dates Filter Design for Leaderboard

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#567]
Above the leaderboard, we would like to implement tabs where users can switch between an "All-time" leaderboard and the different Competition rounds (Competiton #1, Competition #2). 

### Deliverables

- Design Tabs/Filters for different competition rounds
- Tab "Competition 1" should show a Leaderboard for a specific date range (e.g. of the competition)

**Comment by asherism** [comment]
Figma file:
https://www.figma.com/file/YWU3PMsnqZaqr1gABgAFJK/?node-id=862%3A3578

**Comment by asherism** [comment]
Filter icons:
![Inactive Filter](https://user-images.githubusercontent.com/11524787/174140851-d5b6fcb7-c8f3-49ed-a132-7fadad480f1c.svg)
![Active Filter](https://user-images.githubusercontent.com/11524787/174140857-8642884e-601f-49eb-be4d-42341924a849.svg)
