### ISSUE TITLE
Leaderboard UI component for Dashboard

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#569]
### Subject of the issue
Add a leaderboard UI component to the dashboard to quickly show users the top 10 traders of the currently running competition.

# Blocker
Need to revise how (or if) we want to show different tiers here, too. See #design discussion.

### Design
See Figma link in comments below for full design specs.

![Screen Shot 2022-08-03 at 15 22 10](https://user-images.githubusercontent.com/548702/182681165-2c404379-8077-4d09-a0f5-5c9505397b7b.png)

### Deliverables

- [ ] Add the leaderboard component to dashboard (see design)
- [ ] Data to show: Rank (1-10), Trader address (or ENS name), PnL %
- [ ] Show top 10 traders of the current competition round, data to be specified with #820 (*)
- [ ] If no active competition round specified, default to all-time top 10.

### Notes
(*) Dates will be handled by the backend process pulling the respective data, to fetch via the [useGetFile.ts](https://github.com/Kwenta/kwenta/tree/dev/queries/files/useGetFile.ts) hook

### Deadline
August 8th, 2022

**Comment by asherism** [comment]
https://www.figma.com/file/R9dygkd4HBA7PdxtE3iLis/External?node-id=435%3A731

**Comment by asherism** [comment]
<!-- Uploading "image.png"... —>
