### ISSUE TITLE
There is no place on "Futures" page where you can see exact amount (with all decimals) of your longed/shorted asset

### ISSUE THREAD

**Issue by drptbl** [Kwenta/kwenta#59]
### Subject of the issue
There is no place on "Futures" page where you can see exact amount (with all decimals) of your longed/shorted asset. We could show it somewhere on mouse hover. Currently to see exact amount, you have to go to etherscan transaction details.

### Reproduction steps:
1. Go to "sBTC Futures" page (https://kwenta-git-feat-futures-kwenta.vercel.app/futures/market/sBTC)
2. Connect your wallet
3. Create new long position with `0,005717094331770919 BTC` => you are not able to see this exact amount anywhere in the UI, it's shortened everywhere (up to 4 decimals). You have to go to etherscan if you want to check it.

### Your environment
* Optimism Kovan
* Chrome v92.0.4515.159

### Screenshots
<img width="319" alt="Screenshot 2021-09-16 at 00 52 56" src="https://user-images.githubusercontent.com/8177587/133520385-8b0d62bd-bd6a-4b84-9c55-ddd99dc0732a.png">
<img width="427" alt="Screenshot 2021-09-16 at 00 52 41" src="https://user-images.githubusercontent.com/8177587/133520399-775c50a2-68b2-4d1d-b366-74d38f738a39.png">
<img width="1023" alt="Screenshot 2021-09-16 at 00 52 36" src="https://user-images.githubusercontent.com/8177587/133520405-47f0e4b6-82fa-41fb-b084-88cf475e7951.png">

**Comment by platschi** [comment]
In the new layout, this might easily be solved with a hover in the `PositionCard` when hovering over "Position Size"

**Comment by platschi** [comment]
Current layout set to 4 decimals which should suffice even for the smallest 50$ trades on BTC, closing issue for the time being.
