### ISSUE TITLE
support update to next v12

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#596]
### Subject of the issue
Users on M1 machines cannot build the Kwenta repository due to errors with the `sharp` package dependency. This ticket tracks the efforts to update old packages to make it possible for users with M1 Apple machines to run the Kwenta dev environment without any issues or Rosetta hacks.

Updating the `sharp`dependency within `optimized-images-loader` does not resolve the issue. 

Solution:
https://nicedoc.io/cyrilwanner/next-optimized-images

### Scope of ticket

- [ ] Replace `optimized-images-loader` package with `next-optimized-images` in order to be able to build on newer M1s.

**Comment by brossetti1** [comment]
been working on it today and running into a lot of weird problems -- it looks like this package has not been worked on in 2 years, are we sure we want to use this?

most of the images we load are svg - before I go into any issues im encountering, can we discuss considering [SVGR](https://react-svgr.com/docs/what-is-svgr/) which still optimizes using svgo under the hood?

**Comment by koredefashokun** [comment]
Curious what others think about this. I for one would prefer if we used `next/image`, as that would significantly reduce the possibility of running into dev issues. We can also be sure that it would work well with Next.js in general. However, I'm curious to know what decisions went into choosing optimized-images-loader initially.
