### ISSUE TITLE
Refreshing a website on "Market View" page causes an issue with asset image being fetched with "undefined" in url 

### ISSUE THREAD

**Issue by drptbl** [Kwenta/kwenta#62]
### Subject of the issue
Refreshing a website on specific market page causes an issue with asset image being fetched with "undefined" in url.

### Reproduction steps:
1. Go to "sBTC Futures" page (https://kwenta-git-feat-futures-kwenta.vercel.app/futures/market/sBTC)
2. Connect your wallet
3. Refresh a website => error is shown in browser console

### Your environment
* Optimism Kovan
* Chrome v92.0.4515.159

### Screenshots
<img width="731" alt="Screenshot 2021-09-16 at 01 10 11" src="https://user-images.githubusercontent.com/8177587/133524729-9588dfa0-f693-4991-98ad-06751e167a8b.png">

**Comment by clementbalestrat** [comment]
Can't reproduce that one

**Comment by drptbl** [comment]
@clementbalestrat I can reproduce it every time, all you have to do it to go to url above with open browser console.

Check the video to see it:
![2021-09-22 21 04 37](https://user-images.githubusercontent.com/8177587/134406004-c17edee6-57f0-414d-9dc4-ae85c17cda52.gif)

I'm using Chrome Browser.
