### ISSUE TITLE
Let users know that minimum margin amount to open a position is 100$ somewhere in dapp

### ISSUE THREAD

**Issue by drptbl** [Kwenta/kwenta#71]
### Subject of the issue
I had less than 100$ deposited in to my margin and I wasn't really aware why I can't open a new position because dapp doesn't describe the minimum amount that has to be deposited to open up a position.

### Screenshots
<img width="367" alt="Screenshot 2021-09-16 at 02 24 41" src="https://user-images.githubusercontent.com/8177587/133529988-8405110c-bc79-4d41-95f1-f11ad7474ce6.png">

**Comment by drptbl** [comment]
Hey @clementbalestrat, are we doing something about this one? I can't see any related changes.

**Comment by clementbalestrat** [comment]
Yes this is what I did:
<img width="378" alt="Screen Shot 2021-09-23 at 9 32 32 am" src="https://user-images.githubusercontent.com/690350/134435392-0c7e1213-5b69-4c95-8a7d-7d30363686bc.png">

**Comment by drptbl** [comment]
Thanks @clementbalestrat 🙏.
