### ISSUE TITLE
Implement new position card design

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#716]
### Subject of the issue
The current `PositionCard` is being revamped to include more information, most notably the Realized PnL. Additionally, the Close Order button will be moved to another part of the UI.

### Deliverables

Note: In the external designs document (below), please focus only on the first design (to the left). The second design (modified position) will be a separate ticket.

- [x] Implement the new PositionCard design as outlined in the design spec (see comment below).
- [x] Make sure Realized PnL is added and displayed correctly. For questions, ping devDAO PM.
- [x] Move the Close Order button to the right panel, next to Modify/Open Position.
- [x] Implement redesigned Modify position modal
- [x] Add the "Manage - Adjust your position" text above the buttons

### Rewards
50 SNX

**Comment by asherism** [comment]
https://www.figma.com/file/R9dygkd4HBA7PdxtE3iLis/?node-id=141%3A409
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/11524787/163884779-b7246a48-c72a-4d21-a024-60a32250952c.png">
