### ISSUE TITLE
Order History Tab

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#751]
# Work in progress

Implement a order history tab on the Markets page.

### MVP
- Date/Time
- Entry Price
- **Realized** PnL
- Fees paid
- Status

### Optimal Order History Tab 
- Date/Time
- Market
- Side
- Trigger Price
- Fill Price
- Position Size
- Realized PnL
- Fees paid
- Type (Next-Price, Market, Limit, etc.)
- Status

**Comment by brossetti1** [comment]
@platschi got some questions maybe we can chat with the team about this tomorrow.. 

1) do we have a figma for this one? is this it?
https://www.figma.com/file/YWU3PMsnqZaqr1gABgAFJK/UI-Refresh?node-id=652%3A2734 
if so, this seems a little different then the attributes above.

2) what is meant by `Fill Price`? are we talking about entry and exit price there?

@Tburm if you can help with these
3) what attribute should I reference for from the graph? `Type (Next-Price, Market, Cancelled, etc.)`?
