### ISSUE TITLE
Jump to top on page change

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#752]
### Subject of the issue
When visiting a market from the list on the dashboard, on smaller screens there is the need to scroll down the page. When clicking on a market, the markets page opens, however it does not "jump" back to the top of the page, hiding the navigation menu. See screen record.

https://user-images.githubusercontent.com/548702/165176748-8e0e00de-abd7-4bde-9e91-7423ef74b444.mov

### Deliverable
- Make sure the page "scrolls to top" when switching pages

### Reward
25 SNX

**Comment by kethcode** [comment]
This ticket requests behavior that is the default behavior for next.js.  The fact that it is not occurring suggests there is a bug in the UI.

Digging around, I've found multiple suggests on how to work around it, but none of them were effective.

https://github.com/vercel/next.js/issues/28778
https://github.com/vercel/next.js/issues/22858
https://github.com/vercel/next.js/issues/3249#issuecomment-680532902

Most of the reports where this are occurring seem to realte to CSS .  Specifically some sort fo itneraction when these parameters overlap:
```height: 100%;
overflow-x: hidden;```

That's all I've got.
