### ISSUE TITLE
implement time display component

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#771]
### Subject of the issue
Add a time display component which can be later used for various time displays, e.g. on the leaderboard, order history table, etc.

### Deliverables
- Create a clean time display component
- Make sure it switches between 24 and 12h format when clicking on the time
- Show date format according to user locale
- Refactor leaderboard and "Trades" tab to use the new time display component

### Reward
50 SNX

**Comment by 0xwontonsoup** [comment]
@platschi could you show me an example of something that's close to this description?
