### ISSUE TITLE
TradingView: Add more timeframes

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#773]
### Subject of the issue
Implement all relevant time frames:

- [x] 30min
- [x] 2h
- [x] 4h
- [x] 8h
- [x] 12h
- [x] 3d
- [x] 1w
- [x] 1m

**Comment by Tburm** [comment]
@platschi Do you mean to add more intervals here:
<img width="171" alt="image" src="https://user-images.githubusercontent.com/10401554/165824042-45441d28-c7d1-4fea-922e-af34d76401c3.png">


Or add more presets here:
<img width="235" alt="image" src="https://user-images.githubusercontent.com/10401554/165824111-b678e42c-f3b6-4f09-bce8-2163481d5c15.png">

**Comment by platschi** [comment]
> 

Intervals
