### ISSUE TITLE
Upgrade to rainbowkit

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#948]
Implement [rainbowkit](https://www.rainbowkit.com/docs/introduction) instead of `bnc-onboard`

### Deliverables
- replace `bnc-onboard` with `rainbowkit`
- set dark theme/light theme depending on kwenta theme choice of user
- Remove old packages and code related to `bnc-onboard`

Important: Make sure rainbow-wallet works with Gnosis Safe

**Comment by JChiaramonte7** [comment]
Just a caveat with this one, we should make sure this still works w/ Gnosis safe. ie. Make sure you test Kwenta as a gnosis safe app (you can use the deployment URL)

<img width="278" alt="image" src="https://user-images.githubusercontent.com/4015977/174161266-6acf5684-eb2d-4332-94ad-ecbbb98e00ed.png">
