### ISSUE TITLE
Trading History LazyLoad

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#949]
### Subject of the issue
The "Trading History" table on the Markets page is currently showing only the last 50 trades. We want to avoid this limitation and instead lazyload the table infinitely.

### Deliverables
- Replace pagination with lazyload on Trading History and load trades infinitely
-  Remove `DEFAULT_NUMBER_OF_TRADES` limit
- Make sure to show first 16 trades by default
- Change label "Last 50 Trades" to "Last Trades"

### Rewards
25 SNX

**Comment by westonnelson** [comment]
This still need to be worked on???
