### ISSUE TITLE
Implement Share Position Modal for Mobile

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#953]
### Subject of the issue
Mobile users currently can't download the PnL graphic on mobile due to the Share option missing. This is currently only available on desktop. We want to make sure the possibility to Share currently open position is available on mobile. We want to add a share button, and upon clicking it, it should open the responsive (mobile-friendly) image of the PnL graphic, while giving an option to either download it to their mobile devices for further sharing, or directly tweeting it out, similar to the options available on desktop.

### Deliverables

- [ ] Add responsive version of PnL graphic design for mobile (see Figma file below)
- [ ] Add Share button component/functionality to mobile Position card according to design (see Figma & icon file below in comments)
- [ ] Add option in modal to share image on Twitter

* Regarding Share button on mobile position card: The same as the PositionCard, make sure it is only visible when the user has an open position.

* Regarding Tweet button, see Discord conversation.

**Comment by platschi** [comment]
Figma: https://www.figma.com/file/mcaXc01qAA1si3I8shXkeI/Kwenta---Website?node-id=1246%3A2153

**Comment by asherism** [comment]
Updated mobile position card with share button here: 
https://www.figma.com/file/R9dygkd4HBA7PdxtE3iLis/External?node-id=515%3A1032

**Comment by asherism** [comment]
Icon:
![Image](https://user-images.githubusercontent.com/11524787/183492536-6639996b-6cff-460f-909a-c8859219bdc6.svg)
