### ISSUE TITLE
Implement Dark/Light Theme Switch

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#960]
### Subject of the issue
We currently have a Settings button in the top right navigation, which shows a language and theme dropdown. To simplify the UI, we would like to remove this Settings modal and simply show a light/dark mode switch on the navigation button that currently is the Settings button.

### Deliverables
- Make the Settings button a light/dark theme switch, toggling between a moon/sun icon depending on the theme selected (dark or light)
- Remove unused Settings modal code
- button & icon must have hover states (refer to the current settings button styles)
- implementation must use our `selectedTheme` style object

### Reward
25 SNX

### Deadline
Thursday 9 June

**Comment by asherism** [comment]
![Sun](https://user-images.githubusercontent.com/11524787/172478411-5708de60-9ddb-4ea0-85ea-4eb915882b6c.svg)
![Moon](https://user-images.githubusercontent.com/11524787/172478412-e976a407-2122-4758-9d10-7beefba5e207.svg)

-sun.svg for light mode
-moon.svg for dark mode
-button & icon must have hover states(refer to the current settings button styles)
-implementation must use our selectedTheme style object

**Comment by asherism** [comment]
hover states with the selectedTheme object are missing 
unnecessary css leftover from the settings icon
