### ISSUE TITLE
Add Markets to Futures Sidebar

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#978]
### Subject of the issue
Split the current Trade History up into two tabs, one showing available Futures Markets with 24V Volume data, and second tab showing the already existing Trade History:
<img width="704" alt="image" src="https://user-images.githubusercontent.com/11524787/173629658-60af3246-f746-4d59-b9e6-26e543616f05.png">

### Deliverables:
- Add Markets tab to the left sidebar on Markets (see mockup below)
- Load the Markets tab by default
- Load into localstorage last visited tab and keep that visible when switching to other markets

### Reward
150 SNX

**Comment by asherism** [comment]
Figma file here:
https://www.figma.com/file/R9dygkd4HBA7PdxtE3iLis/?node-id=102%3A53

**Comment by westonnelson** [comment]
I'll take this if needed!
