### ISSUE TITLE
Futures Positions table Size issue

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#993]
### Subject of the issue
For orders of a size >1 Million $, the Futures Position tables Size and Leverage values overlap, making it difficult to read values. The table should be more responsive in order to avoid this issue for whales, see screenshot:

![whales](https://user-images.githubusercontent.com/548702/173380692-49bc353e-e2b7-481b-998f-da3502af016c.png)

### Deliverables
- Truncate **Size** values from and above $1.000.00,00 in `FuturesPositionTable` (see conversation below)

### Reward
25 SNX

**Comment by JChiaramonte7** [comment]
What if we start switching to $2.6M instead of $2,651,263.58? At least for this table

**Comment by asherism** [comment]
Agree with Jeremy. Maybe we truncate starting with 100K and upward to 1M.
